### ISSUE TITLE
Could not find BettiNumbers module in source listed as a module as per the documentation

### ISSUE THREAD

**Issue by jitinnair1** [topology-tool-kit/ttk#1026]
**Describe the bug**

I wanted to use TTK to calculate Betti Numbers. I was going through the [developer documentation](https://topology-tool-kit.github.io/doc/html/index.html) and under Modules -> VTK I found a class called `ttkBettiNumbers` (screenshot below). 

However, it is not available in the source files in the latest release. I also checked a few of the older releases but could not find it.

(I am unfamiliar with the Doxygen layout hierarchy so I may be looking at the wrong places perhaps?)

**To Reproduce**
1. Download the latest release
2. Go to `core/vtk`
3. `vtkBettiNumbers`directory is not found 

**Expected behavior**
Find the `ttkBettiNumbers` module in the source files in `core/vtk`

**Screenshots**

<img width="581" alt="Screenshot 2024-05-05 at 12 47 50 AM" src="https://github.com/topology-tool-kit/ttk/assets/2485715/cb4aae1b-c8db-48c3-bf67-7b9aed5fedff">

Here is the link from where this screenshot is: [https://topology-tool-kit.github.io/doc/html/group__vtk.html](https://topology-tool-kit.github.io/doc/html/group__vtk.html)

**System (please complete the following information):**
 - OS: Ubuntu
 - Compiler GCC
 - Installed TTK's optional dependencies None

**Additional context**
I installed `ttk` from source and did not install the optional dependencies. While building I chose to not build the Paraview Plugins.

**Comment by julien-tierny** [comment]
Hi!

thanks for your issue.

Actually, there is indeed no `BettiNumbers` module in the official TTK release. This is a documentation bug (we program this module internally as an exercise for newcomers). This commit (https://github.com/topology-tool-kit/topology-tool-kit.github.io/commit/7cbac85f8618ee13d14f4d5f510973d2ef1f6761) should fix this.

If you want to compute Betti numbers, I'd suggest to proceed as follows:
- compute the persistence diagram of your dataset
- collect the bars for which the cell data array `IsFinite` is set to 0 (these are the essential homology classes)
- the cell data array `PairType` gives you the dimension `p` of the corresponding homology group.

Then, the number of p-dimensional "infinite" bars gives you the p-th Betti number.

I hope this helps.

Best,

**Comment by jitinnair1** [comment]
Thank you for clarifying and fixing this, and also for your suggestion on how Betti numbers could be calculated.
