### ISSUE TITLE
Using namespace

### ISSUE THREAD

**Issue by martinfalk** [topology-tool-kit/ttk#103]
Is there a particular reason for using `using namespace std;` or `using namespace ttk;` in header files?

For example in [core/base/abstractTriangulation/AbstractTriangulation.h](https://github.com/topology-tool-kit/ttk/blob/master/core/base/abstractTriangulation/AbstractTriangulation.h#L18-L20)
and [core/base/common/Debug.h](https://github.com/topology-tool-kit/ttk/blob/master/core/base/common/Debug.h#L38)

This rather pollutes the global namespace as soon as we include any TTK header files. We are trying to include it in one of our projects where we discourage the use of `using namespace` globally, in particular in header files.

**Comment by julien-tierny** [comment]
dear martin,

thanks a lot for your message.

> For example in
> [core/base/abstractTriangulation/AbstractTriangulation.h](https://github.co
> m/topology-tool-kit/ttk/blob/master/core/base/abstractTriangulation/Abstract
> Triangulation.h#L18-L20) 
thanks for catching that one up.
the first one does not seem to be needed indeed.

> and
> [core/base/common/Debug.h](https://github.com/topology-tool-kit/ttk/blob/
ma
> ster/core/base/common/Debug.h#L38)
the code will not build currently if you comment that one out.
I guess we used it for convenience (to avoid putting std:: in front of each 
stl call) and it's all over the code now. I'm not sure whether or not we want 
to change this at the moment.

> This rather pollutes the global namespace as soon as we include any TTK
> header files. We are trying to include it in one of our projects where we
> discourage the use of `using namespace` globally, in particular in header
> files.
would you recommend to include these in *cpp files only instead?
how about inline functions in header files that may still be using calls from 
this namespace?

if you don't mind, unless something is broken on your end, I will close this 
issue and invite you to continue this discussion there: 
ttk-dev@googlegroups.com

please don't hesitate to let us know if you run into any trouble with ttk or 
if you want to provide feedback like you just did. this is always appreciated 
and we're always happy to help.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

On Friday, May 4, 2018 5:37:27 PM CEST Martin Falk wrote:
> Is there a particular reason for using `using namespace std;` or `using
> namespace ttk;` in header files?
> 
> For example in
> [core/base/abstractTriangulation/AbstractTriangulation.h](https://github.co
> m/topology-tool-kit/ttk/blob/master/core/base/abstractTriangulation/Abstract
> Triangulation.h#L18-L20) and
> [core/base/common/Debug.h](https://github.com/topology-tool-kit/ttk/blob/
ma
> ster/core/base/common/Debug.h#L38)
> 
> This rather pollutes the global namespace as soon as we include any TTK
> header files. We are trying to include it in one of our projects where we
> discourage the use of `using namespace` globally, in particular in header
> files.

**Comment by petersteneteg** [comment]
Hi

Imho think you should take the time and remove the using namespace std from all headers now, it will only get harder in the future. It is really bad form to have them in global scope in headers see for example https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#Rs-using-directive

Btw I could only found ttk-users at google groups not a ttk-dev?

**Comment by julien-tierny** [comment]
hi peter,

thanks for these clarifications.
the commit 4a257fc should have fixed this.
thanks for letting us know if it's ok for you guys.
@CharlesGueunet
@GuillaumeFavelier
@madblade
you want to merge that to your own branches asap.

> Btw I could only found ttk-users at google groups not a ttk-dev?
I don't believe it appears in public listings indeed (we may want to change 
that) but it does exist. feel free to shoot an email there for technical 
discussions.

thanks for letting us know how the inclusion of ttk in your project goes.
we're always happy to help.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

On Saturday, May 5, 2018 9:57:11 AM CEST Peter Steneteg wrote:
> Hi
> 
> Imho think you should take the time and remove the using namespace std 
from
> all headers now, it will only get harder in the future. It is really bad
> form to have them in global scope in headers see for example
> https://github.com/isocpp/CppCoreGuidelines/blob/master/
CppCoreGuidelines.m
> d#Rs-using-directive
> 
> Btw I could only found ttk-users at google groups not a ttk-dev?

**Comment by martinfalk** [comment]
Hi Julien,

thanks for the quick response and fixes!

Martin

**Comment by julien-tierny** [comment]
I'm closing that one if you don't mind.
please feel free to re-open it later if needed.
best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
