### ISSUE TITLE
Topomap missing boost dependency

### ISSUE THREAD

**Issue by petersteneteg** [topology-tool-kit/ttk#1033]
**Describe the bug**

When Qhull is not found or if TTK_ENABLE_QHULL is false
the TopoMap module will use boost, but the CMakeList file does not link boost.

Adding this at the end will fix the issue

```
if(NOT TTK_ENABLE_QHULL OR NOT Qhull_FOUND)
  target_link_libraries(topoMap PUBLIC Boost::boost)
endif()
```

**Comment by julien-tierny** [comment]
Thanks a lot for the heads up.
TopoMap built fine under linux without this patch and our windows CI didn't catch up the issue (as it installed QHull).
The PR #1034 should address that. 
Thanks for letting me know if #1034 is OK for you.
Best,

**Comment by petersteneteg** [comment]
Great! that's perfect.
Thank you!

**Comment by julien-tierny** [comment]
thanks a lot for the hot fix!
