### ISSUE TITLE
Vertex Indices do not match after simplification

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#126]
I'm performing a basic task as follows.

- import scalar field and compute persistence diagram
- apply a threshold based on persistence on the persistence diagram
- use the scalar field and persistence threshold for topological simplification
- compute split tree on simplified domain

I perform a matching between nodes in the persistence diagram to that in the split tree.

I have often noticed one of the two anomalies in few nodes.
- The vertex index in the persistence diagram is twice that of the vertex index in the simplified domain

A work around that I used was to compute the vertex indices by multiplying+adding the coordinates of the persistent diagram [using the spreadsheet view - I was using a 3D regular grid and therefore this was possible]. In this case the discrepancy is that, 

- The computed vertex index using the coordinates would sometimes be one less/more than that of the simplified domain. For instance, the mismatch in the coordinates would something be like (29, 35, 42) instead of (28, 35, 42).

Is there something I'm missing with respect to simplification usage or is this a bug?

Cheers!

**Comment by julien-tierny** [comment]
hi there,

thanks a lot for your message.

> I have often noticed one of the two anomalies in few nodes.
> - The vertex index in the persistence diagram is twice that of the vertex
> index in the simplified domain
I'm not sure I can replicate that issue.

First of, can you specify what version of the code you're using? Are you 
using the master branch of the github repository?

Second, can you confirm you're computing the split tree with the FTM module 
(not the ContourForest) one?

In the attached screenshot, you'll see that I replicated the scenario you 
mentioned. 
On the left, you have a split tree based segmentation, with the nodes of the 
split tree shown in a spreadsheet view at the bottom.
On the right, you have the simplified persistence diagram, with the points 
displayed in a spreadsheet view at the bottom.

There, you can verify that for all the nodes of the split tree, there exists 
a unique corresponding point in the diagram such that:
- the PointData field "VertexId" of the split tree equals the PointData 
field "VertexIdentifier" in the diagram

I do not observe any offset or multiplication in the values of these fields.
Obviously you have more persistence pairs in the diagram than represented in 
the split tree (which only tracks [d-1, d] persistence pairs).

Does it clarify your issue?
If not, can you please provide a state file illustrating the issue?

Thanks,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

On Thursday, 5 July 2018 02:58:59 CEST Kamakshidasan wrote:
> I'm performing a basic task as follows.
> 
> - import scalar field and compute persistence diagram
> - apply a threshold based on persistence on the persistence diagram
> - use the scalar field and persistence threshold for topological
> simplification - compute split tree on simplified domain
> 
> I perform a matching between nodes in the persistence diagram to that in 
the
> split tree.
> 
> I have often noticed one of the two anomalies in few nodes.
> - The vertex index in the persistence diagram is twice that of the vertex
> index in the simplified domain
> 
> A work around that I used was to compute the vertex indices by
> multiplying+adding the coordinates of the persistent diagram [using the
> spreadsheet view - I was using a 3D regular grid and therefore this was
> possible]. In this case the discrepancy is that,
> 
> - The computed vertex index using the coordinates is often one less/more
> than that of the simplified domain. For instance, the mismatch in the
> coordinates would something be like (29, 35, 42) instead of (28,35, 42).
> 
> Is there something I'm missing with respect to simplification usage or is
> this a bug?
> 
> Cheers!

**Comment by kamakshidasan** [comment]
Hi there!

I use v0.9.5 downloaded as tarball from TTK's website.

I currently use the FTM module and not the ContourForest. However, I think the doubling of vertex indices was while using ContourForests. I'll try to replicate that and send it across.
 
I have replicated your screenshot for a different different dataset. I'm attaching the state file here. Here's my anomaly: There is node with vertexId "9636" in the split tree. In the original persistence diagram there is no node with that vertexId, however a spatially closer one "9635"exists. After thresholding, this node disappears, I guess because of low persistence.

![vertex-index-issue](https://user-images.githubusercontent.com/9362064/42322812-255d12b6-805e-11e8-9461-f055894de1f1.png)
[bug.pvsm.zip](https://github.com/topology-tool-kit/ttk/files/2166501/bug.pvsm.zip)

**Comment by julien-tierny** [comment]
hi there, 
thanks for your quick feedback.

your screenshot indicates that you forgot to check the box "Use Input Offset 
Scalar Field". 
you need to check this box if you want the split tree to correctly interpret 
the simplification.

if you check this box, you should obtain the desired mapping.

thanks for letting us know if that fixes your issue.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
Hi there!

It finally worked! I should have asked about this much earlier instead of spending sleepless nights figuring a work around! :)

What does the "Use Input Offset Scalar Field" box exactly do? I have taken this box absolutely for granted till now -- on few days I turn it on, on the other I leave it off. :D

In few of my earlier experiments, though I did not perform matching, I have certainly did not check this box. Has the integrity of my experiments changed? Is there way to always check this on by default?

Thanks,

Adhitya

**Comment by julien-tierny** [comment]
hi,

> It finally worked! I should have asked about this much earlier instead of
> spending sleepless nights figuring a work around! :)
sorry about that.
I believe the video tutorials clearly mention to check this box though :(

> What does the "Use Input Offset Scalar Field" box exactly do?
in ttk, vertices are compared based on their scalar value and an injective 
integer offset function. this guarantees the overall injectivity of the 
considered scalar function. this is important to perturbate flat plateaus.

the filter topological simplification modifies the scalar values *and* re-order 
the offset function to make sure it is strictly monotonic on plateaus (to 
effectively perturbate the flat plateaus resulted from the simplification). see 
my ieee vis 2012 paper on the topic for more details.

> What does the "Use Input Offset Scalar Field" box exactly do?
that's a good point, let me see if we can set this by default in the entire 
platform without breaking everything.

as a workaround, in paraview, you have the possibility for each filter to save 
the current settings as default settings (by clicking on the tiny floppy button 
on top of the property panel of the corresponding filter).
then, next time you use the said filter, this box will be checked by default.

hope this helps.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
Thanks Julien, your response is certainly helping me understand much more
of the inner workings of TTK. Special thanks for always responding quickly
- it's like silent encouragement! :)

**Comment by kamakshidasan** [comment]
Hi,

This is also another small bug I have had for a long time now.

By accessing the cell data of arcs for a merge tree, I'm able to the downNodeId and upNodeId. If I save them using the GUI, these attributes get saved to the file.

However, if I do the same action by using Python [after Tracing], I would end up with the Point Data and not the Cell Data. Would you happen to know an argument that I can pass to Paraview's ExportView() asking for Cell Data?

**Comment by julien-tierny** [comment]
hi,
please open a separate issue and copy paste your last comment.
(unless the original issue is not solved).
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
hi,

This comment is related to the above issue. I'll open a new issue if you would like that.

I'm currently using TTK's master branch for running experiments. I perform the same tasks as listed above.

> There, you can verify that for all the nodes of the split tree, there exists
> a unique corresponding point in the diagram such that:
> - the PointData field "VertexId" of the split tree equals the PointData
> field "VertexIdentifier" in the diagram

The issue related to offsets in vertex indices is no longer present. However, I still cannot verify your above statement. There are vertex indices that are present as contour tree nodes but not present in the thresholded persistent diagram.

<img width="1386" alt="persistence-matching-error" src="https://user-images.githubusercontent.com/9362064/42403953-75806d06-8185-11e8-99fb-a965d26d6a53.png">

[bug.pvsm.zip](https://github.com/topology-tool-kit/ttk/files/2172227/bug.pvsm.zip)

Thanks,

Adhitya
