### ISSUE TITLE
vertex indices missing after simplification

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#130]
hi,

I'm currently using TTK's master branch for running experiments. I perform the same tasks as issue #126 

> There, you can verify that for all the nodes of the split tree, there exists
> a unique corresponding point in the diagram such that:
> - the PointData field "VertexId" of the split tree equals the PointData
> field "VertexIdentifier" in the diagram

I cannot verify the above statement. There are vertex indices that are present in the contour tree as  nodes but not present in the thresholded persistent diagram. I'm attaching a screenshot and the state file.

<img width="1440" alt="missing-issue" src="https://user-images.githubusercontent.com/9362064/42413618-4a4710c8-8224-11e8-8b8e-3ca196d7e265.png">

[bug.pvsm.zip](https://github.com/topology-tool-kit/ttk/files/2172991/bug.pvsm.zip)

Cheers,

Adhitya

**Comment by julien-tierny** [comment]
hi,
can you please provide the file "tv_1.vtk" mentioned in your state file.
thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
Sorry about that. Here you go.


[tv_1.vtk.zip](https://github.com/topology-tool-kit/ttk/files/2173004/tv_1.vtk.zip)

**Comment by julien-tierny** [comment]
> Will this be fixed in the future?
if you come up with an algorithm that enforces constraints on boundary saddles 
and you're willing to share its implementation, then probably :)

> This is exactly the work around I use as well!
good. I'll go ahead and close this one then.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
