### ISSUE TITLE
TTK sometimes crashes

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#138]
Steps to reproduce this

- Load the attached file
- Extract Surface
- Triangulate
- FTM

The workaround I use is to always use "CleantoGrid" before FTM. To my memory, this has been around since v0.9.0.

Even if this is expected, it would be nice to have a small error message, instead of crashing. :)

[tv_9.vtk.zip](https://github.com/topology-tool-kit/ttk/files/2270623/tv_9.vtk.zip)

**Comment by julien-tierny** [comment]
the following commit should temporarily fix your issue:
4a53d04e16a40f372634ef99d25451bba8d46a2d

I'll close it for now. 
please feel free to re-open if you observe the issue again.
thanks for your help in bug hunting!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
