### ISSUE TITLE
Computing Persistence Diagram seems to hang

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#140]
Steps to reproduce this
- Load the attached file
- GeometrySmoother
- Elevation
- Persistence Diagram

Surprisingly, FTM does not take a lot of time, and gives results in reasonable time.

[one_leg_jump.006102.ply.zip](https://github.com/topology-tool-kit/ttk/files/2397694/one_leg_jump.006102.ply.zip)

**Comment by julien-tierny** [comment]
hi,

thanks for your message.

> - Load the attached file
ttk assumes that your dataset is made of only one connected component.
use the filter "Connectivity" (and select "Extract Largest Region") and apply 
your pipeline again and that will work.

only for ftm we tried to do something clever to work around the 
disconnectedness but it happens to be a non-sustainable solution. 
we'll drop that in future version.

note also that you can use the plugin "TTK ManifoldCheck" that identifies non 
manifold vertices, edges, triangles, etc.

in the future, if you run into issues with ttk, please run "TTK ManifoldCheck" 
on your data to inspect it prior to reporting an issue (that's how I realized 
you had several connected components).

@GuillaumeFavelier:
can you please go over the documentation of all modules depending on ftm to 
clarify that the input is expected to be connected. please do so for:
- the paraview plugins doc (*xml)
- the doxygen doc (at the base code level, it should be enough)
thx!

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by kamakshidasan** [comment]
Thanks! The connectivity filter works like a charm. :)

**Comment by GuillaumeFavelier** [comment]
Hi,

I'll update the documentation accordingly.

**Comment by kamakshidasan** [comment]
Slightly off-topic:

I created an object and made sure that all components are connected, by inserting a cylinder. 
I took the field to be the Elevation on the Y Axis.

Applying TTK ManifoldCheck, I see that the fields EdgeLinkComponentNumber are in the range [1,2] and VertexLinkComponentNumber = 1

Both connectivity and FTM produce disconnected components. I want a unified tree for the mesh.

How do I make the mesh "connected"?

[petals-3.obj.zip](https://github.com/topology-tool-kit/ttk/files/2423487/petals-3.obj.zip)

**Comment by julien-tierny** [comment]
your dataset does not load here.

plus, the user mailing list (ttk-users@googlegroups.com) seems more 
appropriate for this kind of discussion.

thanks
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
