### ISSUE TITLE
Adding identifiers in TriangulationRequest

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#143]
This is a suggestion and not an issue.

The ttkTriangulationRequest allows quick access to view the face/star of a simplex.

It would be nice if the Cell Data of the plugin would also display the indices from the corresponding domain. This would be helpful during export using SpreadsheetView.

**Comment by julien-tierny** [comment]
if I understand well your suggestion, this is something that can be done 
already (at least for the vertices and cells, if that's enough for you).
call the "TTK Identifiers" plugin before (it will add the vertex identifiers as 
PointData and the cell identifiers as CellData). 
Then, apply "TTK TriangulationRequest".
I believe that pipeline is slightly more generic.

thanks for letting me know if that works for you.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
I see now, TriangulationRequest does not "Keep All Data Arrays".

@GuillaumeFavelier
can you add that in real quick?

thanks
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by GuillaumeFavelier** [comment]
Sure, I'm on it.

**Comment by julien-tierny** [comment]
closing (fixed with be08bcbb51fdad95caef510086f957538263de0d)
thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
