### ISSUE TITLE
Paraview crashes on renaming variable

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#152]
Steps to reproduce this:

- Load the attached VTK file
- Add calculator plugin with sqrt((U * U) + (V * V)) [Do not rename the default scalar 'Result']
- Perform FTM on the VTK file
- Rename calculator plugin from 'Result' to 'magnitude'

Paraview/TTK crashes with the message: 

"[ttkFTMTree] Error : input scalar 0 field pointer is null.
Launch on field : Result
Segmentation fault: 11"

[tv_0.vtk.zip](https://github.com/topology-tool-kit/ttk/files/2478738/tv_0.vtk.zip)

**Comment by kamakshidasan** [comment]
I updated the above comment:

It should be read as, "calculator plugin with sqrt((U * U) + (V * V))"

For some reason, Github needs a space before and after the multiplication sign.

**Comment by julien-tierny** [comment]
hi @Kamakshidasan,
@GuillaumeFavelier's PR #163 should have fixed this.
I'm going to go ahead and close this one.
please feel free to re-open if you run into the same issue again.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
