### ISSUE TITLE
Paraview crashes when loading state with missing file

### ISSUE THREAD

**Issue by kamakshidasan** [topology-tool-kit/ttk#158]
Tried loading https://raw.githubusercontent.com/topology-tool-kit/ttk-data/master/states/persistenceClustering0.pvsm without the necessary files.

ERROR: In /Users/adhitya/ttk/ParaView-v5.5.0/VTK/IO/Infovis/vtkDelimitedTextReader.cxx, line 734
vtkDelimitedTextReader (0x7fd59c6b0e80): caught exception: Unable to open input file clustering0.csv

Warning: In /Users/adhitya/ttk/ParaView-v5.5.0/VTK/Imaging/Hybrid/vtkGaussianSplatter.cxx, line 209
vtkGaussianSplatter (0x7fd59f5d1590): No POINTS!!

[ttkPersistenceDiagram] Starting computation on field `SplatterValues'...
Segmentation fault: 11

**Comment by julien-tierny** [comment]
hi @Kamakshidasan,
@GuillaumeFavelier's PR #163 should have fixed this.
I'm going to go ahead and close this one.
please feel free to re-open if you run into the same issue again.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
