### ISSUE TITLE
ParaView crashes if TTKCinemaWriter is not given a path

### ISSUE THREAD

**Issue by EthanS94** [topology-tool-kit/ttk#160]
@JonasLukasczyk : for state file provided to LANL, crash occurs if no cinema DB path is provided and TTKCinemaWriter is shown (eye clicked)

**Comment by julien-tierny** [comment]
hi @EthanS94,
@JonasLukasczyk 's PR #162 should have fixed this.
I'm going to go ahead and close this one.
please feel free to re-open if you run into the same issue again.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
