### ISSUE TITLE
TTKCinemaWriter should add .cdb to path if it is not provided

### ISSUE THREAD

**Issue by EthanS94** [topology-tool-kit/ttk#161]
Currently if a Cinema Database path does not end in .cdb, the TTKCinemaWriter throws an ambiguous error. 

Either a popup with a correct error should be created, or .cdb should be automatically appended to path.

@JonasLukasczyk

**Comment by julien-tierny** [comment]
hi @EthanS94,
@JonasLukasczyk 's PR #162 should have fixed this.
I'm going to go ahead and close this one.
please feel free to re-open if you run into the same issue again.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
