### ISSUE TITLE
DebugLevel to OFF 

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#185]
Can it possible to completely desactivate the logs with a DebugLevel = 0 . 

We tried setting DebugLevel = 0, but it seems that it is defaulting back to  DebugLevel = 1. 

If someone uses a TTK filter in a loop but wants to check to is own cout, it is really hard to find between the highly lenghty logs of TTK.

**Comment by julien-tierny** [comment]
> Can it possible to completely desactivate the logs with a DebugLevel = 0 . 
that is the purpose of ttk's debug level but apparently some ttk dev forgot to conform to it.
I'm going to make a pass on the different modules but that would already be helpful if you could start by giving me a list of ttk modules for which you observed this undesired behavior.

> If someone uses a TTK filter in a loop but wants to check to is own cout, it is really hard to find between the highly lenghty logs of TTK.
I understand. DebugLevel = 0 should be quiet. I'll work on it.

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi jonathan,

the following commits should have fixed this issue:
b77ba74f5df846659f2ed1ee51a2e44f4d230105
747612572ecb34b9fb21ac8cc1c90e6395009f75
691d77c76df949247e9fd76f1ef198ae9fa62b83
72ca78d4c97b0b4938bcc24a76c8468b0ca0ef42
182ed7322e56a06c7241df6ac6ff6b01de05d8a8
116c333601434591eba8b5958a6a79413a0b9d76

please feel free to re-open the issue if you encounter problems again on this front.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
