### ISSUE TITLE
Implicit triangulation has int overflow in vertex count computation

### ISSUE THREAD

**Issue by klacansky** [topology-tool-kit/ttk#195]
If the multiple of the dimensions is greater than 2^31-1 it will overflow and set incorrect number of vertices.

https://github.com/klacansky/ttk/commit/cc6d6b708b183b7ea85b57565fc438abf4f1c4c9

**Comment by julien-tierny** [comment]
hi pavol,

thanks for the issue and the fix. good catch!

as you probably noticed, building ttk with TTK_ENABLE_64BIT_IDS=ON is supposed to take care of that (but it still requires your fix though).

can you please remove these debug printfs (core/base/ftmTree/FTMTree_CT.h, core/base/ftmTree/FTMTree_MT.h) and make a pull request?

thanks!
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by klacansky** [comment]
Done, I will put some other overflow into the FTM issue.
