### ISSUE TITLE
Error while Building TTK

### ISSUE THREAD

**Issue by mzdaly** [topology-tool-kit/ttk#214]
I am using a mac, running Mojave (10.14.4). I am fairly confident I have done all the steps correctly but I run into the following error while compiling ttk:

`In file included from /Users/Matt/ttk/ttk-0.9.7/core/vtk/ttkOFFWriter/ttkOFFWriter.cpp:7:
In file included from /usr/local/Cellar/vtk/8.1.2_3/include/vtk-8.1/vtkDoubleArray.h:29:
In file included from /usr/local/Cellar/vtk/8.1.2_3/include/vtk-8.1/vtkAOSDataArrayTemplate.h:35:
In file included from /usr/local/Cellar/vtk/8.1.2_3/include/vtk-8.1/vtkGenericDataArray.h:72:
In file included from /usr/local/Cellar/vtk/8.1.2_3/include/vtk-8.1/vtkGenericDataArrayLookupHelper.h:26:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/cmath:313:9: fatal error: no member named 'signbit' in the
      global namespace
using ::signbit;
      ~~^`

Thanks ahead of time!

**Comment by jalevine** [comment]
Matt,

Please see this issue as recently discussed in the ttk-users google group:
https://groups.google.com/forum/#!topic/ttk-users/_2GKLSS4ZB0

High-level: 
(a) TTK is not yet fully tested on Mojave (you'll note the most recent OSX installation considered High Sierra: https://topology-tool-kit.github.io/installation-osx.html)
(b) There appears to be an issue with how CMake identifies the certain portions of the C++ library and in particular which portion of XCode it points too and (perhaps) how all of this links against homebrews version of VTK.
(c) There is a bit of a workaround by forcing CMake to look for certain files in certain paths.  It's ugly and not something we want to move to long term, but it might work for you in a pinch.  In the meantime, we're delaying a bit to see how these get resolved once versions settled down on Mojave, homebrew, and vtk/ParaView

**Comment by julien-tierny** [comment]
hi there, 
there does not seem to be a lot of discussion regarding this build chain issue. I'm going to go ahead and close that issue. feel free to re-open if needed.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
