### ISSUE TITLE
valence overflows in FTM computation

### ISSUE THREAD

**Issue by jalevine** [topology-tool-kit/ttk#223]
**Describe the bug**
type valence is defined in core/base/ftmTree/FTMDataTypes.h as unsigned char, which causes FTM tree computation to loop indefinitely.

In particular, the loop in core/base/ftmTree/FTMTree_CT.cpp for FTMTree_CT::leafSearch():

for (valence n = 0; n < neighNumb; ++n) {
}

Repeats indefinitely if neighNumb > 255

**To Reproduce**
I tested this using a sphere mesh, which has a high valence vertex (neighNumb = 288) at poles.

**Expected behavior**
The problem I see here is not the cap on valence sizes, but rather that the default behavior is for the plugin to hang indefinitely (when n = 255, n+1 = 0, so the loop repeats).  I don't know the best fix, but I can see a few:

(1) Putting explicit checks for overflow in the loops, so that at least a warning is thrown.
(2) Using a larger type for valence (i changed valence to be an unsigned int and things work fine).  Of course this comes with a penalty in memory consumption.
(3) Like (2), but with options set at compile time through CMake?
(4) Recoding the loop so that it does not rely on less-than checks.

**System (please complete the following information):**
 - OS: OSX Mojave, 14.4

**Comment by julien-tierny** [comment]
hi josh,

thanks for posting the issue.

> type valence is defined in core/base/ftmTree/FTMDataTypes.h as unsigned char,
that does not look good indeed.
this kind of types should align with the Triangulation's types, whose encoding are already tunable at the cmake level.

in this case, valence should be encoded with SimplexId (return type of getVertexNeighborNumber(), see a few lines above).

@CharlesGueunet: 
did you implement other low level types which do not align with Triangulation's ones?
how about FTR?
if so, thanks for fixing all of those.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
commit eb54d0a should fix the issue.
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jalevine** [comment]
I can confirm it is fixed on my installation too.  Thanks!

**Comment by julien-tierny** [comment]
I'll go ahead and close that one.
please feel free to re-open if needed.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
