### ISSUE TITLE
Provide scripts to automate Docker launches

### ISSUE THREAD

**Issue by cgarth** [topology-tool-kit/ttk#247]
Use cases
- [ ] Run python scripts through Docker pvpython
- [ ] Run pvserver in Docker and pvpython locally, with automatic connection

Works in special cases:
```
alias pvpython="docker run -it -v $(PWD):/home/paraview -p 11111:11111 --rm chgarth/ttk:master pvpython"
```

**Comment by julien-tierny** [comment]
as a side note, the latest ubuntu lts (18.04) provides paraview 5.4.1 with apt-get. that version is a little old but I guess that would be great to have a ttk docker image for that one, such that ubuntu users could run ttk very easily.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
connect paraview gui directly to the local server: 
```
$ paraview --server-url=cs://127.0.0.1:11111
```

**Comment by julien-tierny** [comment]
the following two scripts should do the job

scripts/docker/runTTKPythonDocker.sh
scripts/docker/runParaViewTTKDocker.sh

for some reason though, the output files saved during the execution of python scripts with the docker pvpython do not appear on the host. 

@cgarth: would you happen to know how to quickly fix this?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
it seems that the scripts currently sitting in the source tree solved this issue. please feel free to re-open if needed.
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
