### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by JoyMonteiro** [topology-tool-kit/ttk#248]
Hello,

Are there separate python bindings for TTK, or is it only usable when Paraview in installed?

There is interest in the Met-Ocean community to use topological methods, and python is part of our regular workflow. However, requiring Paraview (or pvpython) makes it harder to adopt TTK since Paraview is not a usual part of our workflow.

**Comment by julien-tierny** [comment]
hi, 

thanks for your message.

> Are there separate python bindings for TTK, or is it only usable when Paraview in installed?
for your information, python examples have been updated recently to illustrate ttk's usage without pvpython: https://github.com/topology-tool-kit/ttk/tree/master/examples/python

> There is interest in the Met-Ocean community to use topological methods, and python is part of our regular workflow. However, requiring Paraview (or pvpython) makes it harder to adopt TTK since Paraview is not a usual part of our workflow.
at the moment, however, paraview is still a dependency for ttk support under python.
we have reasons to believe that, although removing the paraview dependency would make ttk/python installation easier, it would also make it **much** less usable.

we are currently exploring the possibility of releasing binary distributions of paraview/ttk (@cgarth recently looked into providing a ubuntu .deb package), although this looks like a downstream work load. 

we recently put together docker virtual machines (https://github.com/topology-tool-kit/ttk/tree/master/scripts/docker), which is a convenience for people wanting to easily give ttk a try without having to go through a full installation.

regarding python communities, it seems that a more relevant route would be to provide binary distributions of paraview/ttk through anaconda (or any other similar binary package manager).

if you have yourself some experience in packaging software for python package managers, we'd be happy to help you make paraview/ttk available in anaconda for instance.

thanks for your feedback.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JoyMonteiro** [comment]
I hadn't seen the new examples, thanks for pointing them out.

I have seen the TTK gallery and certainly appreciate the capabilities
that come because of paraview integration. 

However, in a couple of recent projects that I have worked on, all we needed was to calculate split/merge trees and then pass on that information further up the pipeline. While currently
this part is custom code, it would be great if we could have used something like TTK. 

Future projects might also have similar requirements, and having Anaconda and Paraview as
dependencies for using a library that in principle has no such dependencies will make it
difficult to distribute our own projects as well (a very real problem even right now!).

I understand if you don't wish to maintain two sets of Python bindings. If I find some
time in the future, I might try to write these bindings myself using pybind11.

Thanks again!

**Comment by lhofmann** [comment]
There is a way to get *VTK* python bindings (as opposed to ParaView python bindings) almost "for free", which is exactly what would be needed here (no need to get into pybind11). It is trivial with the upcoming ParaView 5.7 / VTK 9.0 versions, and with some effort also doable for previous versions.
I have recently put together a "minimal" example that works with both the previous and current versions here: https://github.com/lhofmann/paraview-vtk-template (see https://github.com/lhofmann/paraview-superbuild-docker/blob/master/.travis.yml for continuous integration of this example).
With this, one could put together a ttk python module, that would only depend on a vtk python module (which is already available on anaconda) and not on ParaView. This would also make it much easier to interface with other libraries such as numpy.
Please let me know, if you are interested in this, and/or need more input on this topic @julien-tierny.

**Comment by JoyMonteiro** [comment]
@lhofmann this looks interesting. If I understand your repository, it should be possible to
define a file like `vtk.module` that allows the build system to build python binding to
ttk.

This sounds great! There is also a [pypi](https://pypi.org/project/vtk/#description) vtk distribution.
is this identical to the anaconda distribution? or has it been discontinued in favor of anaconda packages (I noticed that the conda package is newer than the pypi version).

**Comment by julien-tierny** [comment]
hi lutz,

thanks a lot for your message.

> It is trivial with the upcoming ParaView 5.7 / VTK 9.0 versions,
that's awesome. you should get in touch with @CharlesGueunet who is in charge of porting ttk's cmake to pv5.7/vtk9 (see the experimental branch).

> With this, one could put together a ttk python module, that would only depend on a vtk python module (which is already available on anaconda) and not on ParaView. This would also make it much easier to interface with other libraries such as numpy.
that would be terrific if you could put that together, especially if that could be made available in anaconda.

so, yes, definitely interested. please ping @CharlesGueunet.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi there,

@lhofmann did a great job at inserting a VTK/Python API which enables python users to use TTK without installing paraview.
lutz also prepared a conda package, see the instructions below:
https://github.com/topology-tool-kit/ttk/tree/master/examples/python

that closes that issue indeed. 
thanks to all :)

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by JoyMonteiro** [comment]
This is great news!! Thanks...
