### ISSUE TITLE
Rich and complete example

### ISSUE THREAD

**Issue by 461353349** [topology-tool-kit/ttk#255]
Examples are the important tools for understanding the project. Especially when the deployment is not fluent on the Windows platform.
For now only one example, and I donnot think it is complete for no quad mesh output. Could you rich the examples so that TTK could be applied in more areas?

**Comment by julien-tierny** [comment]
please see the following video tutorial for a detailed quad-meshing example:
https://youtu.be/eNW8l5PlgpU
as shown in the video (7:30), the output quad mesh can be saved in a variety of file formats (vtu, off, obj, etc.).
cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
