### ISSUE TITLE
PR #236 introduced bugs in point data arrays copies

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#257]
**Describe the bug**
The newly suggested management for the copy of the input point data arrays onto the generated outputs introduced new bugs. 
Some data arrays are no longer copied. This in particular verifiable with the default ttk example states/viscousFingering.pvsm from the ttk-data repository.
In that example, the list of output point data arrays for TTKScalarFieldCriticalPoints2 is:
- concentration
- CriticalType
- IsOnBoundary
- ttkVertexScalarField
- velocity
- vtkValidPointMask

While it should (and used to) be:
- concentration
- CriticalType
- height
- IsOnBoundary
- OutputDistanceField
- RegionId
- SeedIdentifier
- ttkVertexScalarField
- velocity
- VertexNumber
- vtkValidPointMask

An instance of consequence is that the "finger tips" (large spheres) are no longer colored by seed identifier. See the following screenshots.
before:
![before](https://user-images.githubusercontent.com/3018628/63497165-8aed8700-c4c3-11e9-9d81-273bb260095c.png)
after:
![after](https://user-images.githubusercontent.com/3018628/63497173-8f19a480-c4c3-11e9-9aa5-029c6b1c8b8c.png)

**To Reproduce**
Steps to reproduce the behavior (from the ttk-data directory):
$ paraview states/viscousFingering.pvsm

**Expected behavior**
Described above.

**Screenshots**
Given above

**System (please complete the following information):**
 - OS: [e.g. iOS] gentoo linux
 - Compiler [e.g. 22] gcc 8.2.0
 - Installed TTK's optional dependencies: all

**Additional context**
this one is for @pierre-guillou who authored PR #236

**Comment by pierre-guillou** [comment]
I can reproduce this behavior on my laptop.
After some bisection, the culprit seems to be afdc4f2b.
Fix very soon.

**Comment by julien-tierny** [comment]
PR #260 seems to solve the issue.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
