### ISSUE TITLE
Possible API simplification

### ISSUE THREAD

**Issue by petersteneteg** [topology-tool-kit/ttk#274]
Hi

I have a issue / question. In TTK you have a common pattern where you have a class say MorseSmaleComplex that holds a MorseSmaleComplex2D and a MorseSmaleComplex3D and then a AbstractMorseSmaleComplex pointer to the currently active one. Similar setups occur in a few places. The problem I ran into was calling MorseSmaleComplex::setDebugLevel and I did that directly after constructing the MorseSmaleComplex and hence the AbstractMorseSmaleComplex pointer was not set, and all I got was a "-1" as a return code that I ignored. 

This behavior means that the order of my function calls become very important, for calls that look very innocent. 

My suggestion would be to have  MorseSmaleComplex::setDebugLevel set the debug level for both the MorseSmaleComplex2D and MorseSmaleComplex3D instead. Then the call would always work. A similar change for setThreadNumber and setWrapper might be reasonable.

Would it be possible to have the assertions (TTK_ENABLE_KAMIKAZE) actually assert instead of just returning a -1 of maybe throw an exception.if the error really is a run-time error not a programming error. The current API become quite tedious to work with in this regard.

**Comment by julien-tierny** [comment]
hi peter,

thanks for your message.

> The problem I ran into was calling MorseSmaleComplex::setDebugLevel and I did that directly after constructing the MorseSmaleComplex and hence the AbstractMorseSmaleComplex pointer was not set, and all I got was a "-1" as a return code that I ignored. 
I understand. that's unfortunate indeed.

> This behavior means that the order of my function calls become very important, for calls that look very innocent. 
agreed.

> My suggestion would be to have  MorseSmaleComplex::setDebugLevel set the debug level for both the MorseSmaleComplex2D and MorseSmaleComplex3D instead. Then the call would always work. A similar change for setThreadNumber and setWrapper might be reasonable.
sounds very reasonable indeed. would you mind putting the pr together?

> Would it be possible to have the assertions (TTK_ENABLE_KAMIKAZE) actually assert instead of just returning a -1 of maybe throw an exception.if the error really is a run-time error not a programming error. 
> The current API become quite tedious to work with in this regard. 
that implies many small-scale changes.
ttk uses no assert at all at the moment. 
from my understanding, exceptions and asserts have quite a negative impact on time performance, but I may be wrong.

> The current API become quite tedious to work with in this regard. 
you mean with the C-style returned values?

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by petersteneteg** [comment]
Hi

Thanks for the response. If I find some time I will do a PR for the setDebugLevel and related functions. 

Regards to the TTK_ENABLE_KAMIKAZE. I would say that what you have there is actually assertions. But with the *downside* that you don't terminate the application. Let me explain, in most cases, at least in the ttk code I have read, the check in the TTK_ENABLE_KAMIKAZE sections do contract checks on the input given to the function. Did I get a valid index, was the right preprocess step called, and so on. When you run into any of these issues there is usually nerver anything you can do at runtime. You generally have to stop and change the calling code, make sure you give a valid index, call the preprocess function etc. Hence there is very little to gain from trying to report and handle such errors at runtime, it is better to just fail fast and assert. Doing this also frees up the return value to be used for actually returning useful data instead, generally making code more readable. 

With respect to performance an assertion is usually only enabled when developing or debugging, and never in a release build. Similar to how you do the TTK_ENABLE_KAMIKAZE right now. So there should be no performance cost with respect to using assertions at all. It might even improve performance a bit by freeing up use of the return value channel.

For things that are runtime errors and that you can recover from one can return codes, or exceptions, or a few other techniques. They all come with their pros and cons. As a C++ programmer I would argue that using exceptions is the easiest way of doing that. It removes a lot of the very tedious return code error checking from the code, and allows one to focus on writing code for the success path. With respect to performance, it is hard to find solid evidence, since it is very hard to construct a fair comparison. But the general opinion seems to be that as long as you don't actually throw an exception the runtime overhead should be minimal. There is a space overhead in that the application binary will be a bit bigger, but in our field that should not matter much. And for the exceptional case where one throws an exception, that should generally not happen very often and hence its performance is not a high priority. 

well that my 2 cents anyway :)

**Comment by julien-tierny** [comment]
hi peter,

thanks for your detailed answer.

> Regards to the TTK_ENABLE_KAMIKAZE. I would say that what you have there is actually assertions. 
to some extent yes.

> But with the *downside* that you don't terminate the application.
absolutely. I guess we did not see this as a downside initially :)

> When you run into any of these issues there is usually nerver anything you can do at runtime.
well, what we do at the moment (or what should be done at least) is to report an error message.

> Hence there is very little to gain from trying to report and handle such errors at runtime, it is better to just fail fast and assert. Doing this also frees up the return value to be used for actually returning useful data instead, generally making code more readable. 
I guess that's an interesting discussion point. 
are you making the trip to vis by any chance? if so, we could all discuss that there (if not, others could jump in the discussion as well @CharlesGueunet @JonasLukasczyk @pierre-guillou in this thread)

if the other devs are on board, asserts are things we could move to towards the 1.0 release.

in the meantime, if you could put the PR together for the setters on the msc complex, that'd be great :)

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi peter,

I'm going to go ahead and close this one.

@GuillaumeFavelier PR'ed a hotfix (#278) for the ms-complex, that should be generalized in the new internal API we're currently putting together. see the "dev" branch.

regarding your remarks about templating the base layer functors (ttk-dev mailing list), this is now done (see PR #305, observed perf gains: between 1 and 60%, depending on using 1 or multiple threads, implicit or explicit triangulations). this still has to be generalized to all modules. we'll progressively migrate them towards the release of 0.9.9.

regarding the TTK_ENABLE_KAMIKAZE macro, we opted to keep it in for now as we believe it's useful to be able to turn it on or off independently of the Debug or Release build mode.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
