### ISSUE TITLE
Remove static variables in Topological compression base code

### ISSUE THREAD

**Issue by CharlesGueunet** [topology-tool-kit/ttk#279]
**Bug:**

`SIGABRT` when closing ParaView.

**To Reproduce:**

Open ParaView with the TTK plugin loaded
No filter needs to be called
Close ParaView.

**System:**

 - OS: Arch Linux
 - Compiler GCC 9.2.0
 - ParaView 5.7.0 Patched on the experimental branch

**Additional context:**

This bug is due to #277 
The changes in core/base/topologicalCompression/TopologicalCompression.cpp have introduced 
some static variables. This mean that some memory is allocated each time paraview is launched.
I am not sure why these static variables induce a crash, it should not. Anyway, I would still argue to replace them with internal fields to avoid allocating the memory each time paraview is launched.

**Suggested changes:**

I am not on the current master so I can't do that easily:

``` diff
diff --git a/core/base/topologicalCompression/TopologicalCompression.cpp b/core/base/topologicalCompression/TopologicalCompression.cpp
index c7160a678..ef1fa1401 100644
--- a/core/base/topologicalCompression/TopologicalCompression.cpp
+++ b/core/base/topologicalCompression/TopologicalCompression.cpp
@@ -9,15 +9,13 @@ ttk::TopologicalCompression::TopologicalCompression() {
   nbSegments = 0;
   nbVertices = 0;
   rawFileLength = 0;
+  magicBytes_ = "TTKCompressedFileFormat";
+  formatVersion_ = 1;
 }
 
 ttk::TopologicalCompression::~TopologicalCompression() {
 }
 
-const std::string ttk::TopologicalCompression::magicBytes_{
-  "TTKCompressedFileFormat"};
-const unsigned long ttk::TopologicalCompression::formatVersion_{1};
-
 // Dependencies.
 
 #ifdef TTK_ENABLE_ZFP
diff --git a/core/base/topologicalCompression/TopologicalCompression.h b/core/base/topologicalCompression/TopologicalCompression.h
index a672b95ec..7b13617a1 100644
--- a/core/base/topologicalCompression/TopologicalCompression.h
+++ b/core/base/topologicalCompression/TopologicalCompression.h
@@ -422,10 +422,10 @@ namespace ttk {
     char *fileName;
 
     // Char array that identifies the file format.
-    static const std::string magicBytes_;
+    std::string magicBytes_;
     // Current version of the file format. To be incremented at every
     // breaking change to keep backward compatibility.
-    static const unsigned long formatVersion_;
+    unsigned long formatVersion_;
   };
 
   // End namespace ttk.
```

**Comment by julien-tierny** [comment]
thanks for catching that up!
that was causing segfaults at the exit of the standalone binaries as well.
commit 1a6a122 should fix this.

please feel free to re-open if you still run into issues with this.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
