### ISSUE TITLE
TTK dev branch does not build with Ninja on Arch

### ISSUE THREAD

**Issue by pierre-guillou** [topology-tool-kit/ttk#298]
Trying to build TTK dev branch with CMake/Ninja leads to the following Ninja error:

```ninja: error: build.ninja:32792: multiple rules generate ../core/vtk/ttkAddFieldData/ttk.module [-w dupbuild=err]```

The build stops before anything has been compiled.
Corresponding build.ninja file is available from my website: https://pierre.guillou.net/build.ninja

To reproduce:
1. switch to the dev branch
2. configure a new build directory: `cmake -GNinja $path_to_ttk_sources`
3. try to build it: `ninja`

System:
* up-to-date ArchLinux
* Ninja 1.9.0-2
* CMake 3.16.1-1

Possible workarounds:
* using Make
* using `ninja -w dupbuild=warn`: this generates a warning per VTK filter that looks like

```ninja: warning: multiple rules generate ../core/vtk/ttkAddFieldData/ttk.module. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]```

but TTK builds anyway.

@CharlesGueunet  can you please look at it 😄  ?

**Comment by CharlesGueunet** [comment]
This bug is due to a bug on cmake when dealing with file dependencies: see [this issue](https://gitlab.kitware.com/cmake/cmake/issues/20181).

We can remove the problem on the TTK side by removing the `set_property` in **CMake/VTKModule.cmake**:
https://github.com/topology-tool-kit/ttk/blob/64ea6241c1fb9d9205cd7f375bc22660b4b73bb9/CMake/VTKModule.cmake#L5
Then, the error occurs in VTK...

**Comment by pierre-guillou** [comment]
Thanks @CharlesGueunet for having looked at this issue.
If I understand correctly, we have to wait till the resolution of the issue in CMake.
For now I'll be using either `ninja -w dupbuild=warn` or removing the `set_property` statement in my local repository.

**Comment by pierre-guillou** [comment]
Small update: since CMake 3.17, the generation phase ends in error by calling `ninja -t cleandead` and `ninja -t recompact`. These two commands fail due to the same `dupbuild=err` problem. 

Fortunately, these errors occur after the generation of the build.ninja file and have no consequence on the build process: calling `ninja - w dupbuild=warn` afterwards still builds TTK correctly.

**Comment by julien-tierny** [comment]
this seems to be fixed with cmake-3.17 and ninja 1.10.
closing.

**Comment by pierre-guillou** [comment]
I still experiment the issue with cmake 3.18 and ninja 1.10 on Archlinux with a newly configured build directory. The relevant issue in the cmake bug tracker is also still open (maybe the work on including TTK inside the ParaView superbuild will give it more attention).

I just tested on a Ubuntu 20.04 machine (cmake is 3.16, ninja is 1.10) and the problem occurs there too.
