### ISSUE TITLE
Trouble running c++ example with 64bit on

### ISSUE THREAD

**Issue by dbanesh** [topology-tool-kit/ttk#337]
I'm having trouble running the stable branch of ttk_master with the 64 bit marker turned on for a very large data set. I've also had issues trying to run older version of ttk with 64 bit on (for the same data), but considering that master is the latest, the issue I describe will be based on the output I got with this version. 

0. (On a linux system)
1. I am not compiling TTK with Paraview or VTK, this is for the standalone c++ compilation with 64Bit ON. 
2. Once compiled. I am able to compile and make the c++ example (in examples/c++). I update the 'ints' in the main.cpp file to 'long long int' to support the larger data. Otherwise, the code is 'killed' almost immediately. No other changes are made to the code.
3. The code enters the block for 'Persistence Curve' and breaks. The outputs ttk generates are:

[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |/ _ \
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | | (_) |
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | |\__, |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|  /_/
[Common]                                         \_\  /_/
[Common] Welcome!
[main::load] Reading input mesh...
[main::load]   done! (read 419430400 vertices, 838778882 triangles)
[OneSkeleton] Edge-list built in 122.062 s. (1258209281 edges, 1 thread(s)).
[ZeroSkeleton] One-skeleton built in 271.815 s. (56 thread(s)).
Killed

**Expected behavior**
I expect the sample code to run to completion.

**Screenshots**
<img width="574" alt="Screen Shot 2020-03-03 at 5 39 42 PM" src="https://user-images.githubusercontent.com/19173085/75900522-4475cf00-5dfa-11ea-9f61-93f1add79c08.png">

**System (please complete the following information):**
 - OS: Linux
 - TTK built with cmake 3.15.3, boot 1.70.0 and gcc 9.2.0
 - No additional TTK optional dependencies installed. All Paraview plugins, standalone apps, vtk wrappers turned off.

**Comment by julien-tierny** [comment]
PR #560 should have fixed the issue.
