### ISSUE TITLE
Installation issue: Blank welcome screen

### ISSUE THREAD

**Issue by sdgithub** [topology-tool-kit/ttk#345]
Hello,

I have installed paraview 5.6.1 with ttk 0.9.8. The installation was clean. However, whenever I start paraview from terminal it ends up with a blank paraview screen. I have attached a sample screen. My workstation has a GTX 2080 Ti card installed with necessary cuda 10.2 drivers (Driver version 440.33.01). Could this be due to library conflict? If I need to unsinstall should I just overwrite existing files with a fresh installation. I would be happy to provide any additional information you need. Let me appreciate any suggestions regarding this. 

![screen_1](https://user-images.githubusercontent.com/4682139/80497690-6e75e880-8988-11ea-9794-23030ec03f3e.png)
![screen_2](https://user-images.githubusercontent.com/4682139/80497711-73d33300-8988-11ea-87f7-ebf090751b49.png)

**Comment by julien-tierny** [comment]
hi,

thanks for your message.

the black user interface is a known issue which has been discussed several times on the ttk-users mailing list (https://groups.google.com/forum/#!forum/ttk-users)

it's actually an upstream bug at the Qt5 level in ParaView (issue with the newest OpenGL support in ParaView).

when you configured ParaView's build (step 5a of https://topology-tool-kit.github.io/installation.html), didn't you get any warning like:
```
Qt '5.6.2' found and will be used. Note, however, that the officially
supported version is 5.9.
```

I'd either recommend to make sure you're building ParaView against Qt5.9 or to build an earlier version of ParaView (v5.4.1), whose legacy OpenGL support is compatible with older Qt versions (make sure to set the option VTK_RENDERING_BACKEND=OpenGL1).

thanks for letting us know if you run into further issues.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by sdgithub** [comment]
Hello,

Thanks very much for the response. Unfortunately, trying to build paraview 5.4.1 with rendering backend set to opengl1 results in a failure in the make -jN step. One another issue is that my qmake --version returns the qt version to be 5.9.5. Therefore, I was assuming previously that paraview 5.6.1 was being built using the supported Qt version. Looking forward to any further suggestions. Thanks again.

Regards
Somenath Das

**Comment by julien-tierny** [comment]
hi,

thanks for your message. 

I suggest at this point that you send an email to the ttk-user mailing list <ttk-users@googlegroups.com> to describe your issue (please include information about your OS, distribution, version) and ask for the advice of the users who ran into that issue.

as this is an upstream bug, I will close your issue (there's literally nothing we can change in ttk's source code to fix that).

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
