### ISSUE TITLE
running python example 'topologytoolkitPython.ttkPersistenceCurve' object has no attribute 'SetDebugLevel'

### ISSUE THREAD

**Issue by michalstepniewski** [topology-tool-kit/ttk#352]
python3.7 example.py ../data/inputData.vtu
Traceback (most recent call last):
  File "example.py", line 50, in <module>
    curve.SetDebugLevel(3)
AttributeError: 'topologytoolkitPython.ttkPersistenceCurve' object has no attribute 'SetDebugLevel'

**Comment by julien-tierny** [comment]
hi michal,

thanks for your message.

I can't reproduce your issue here with the dev branch of ttk (tested with python 3.5, 3.6, 3.7, 3.8).
what version of ttk are you using?

cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by michalstepniewski** [comment]
Hello :)
Thank You for your swift answer.

I am using Anaconda with Python3.7

I am applying the instructions contained in:
    https://github.com/topology-tool-kit/ttk/tree/stable/examples/python

**Comment by tbmasood** [comment]
I guess the call here should be curve.SetdebugLevel_(3), not curve.SetDebugLevel(3).

**Comment by julien-tierny** [comment]
thanks @tbmasood for the hint.

@michalstepniewski
it looks like you're trying to run the example from the dev branch while the anaconda package ships the latest stable release.

with the anaconda package, you want to run the example from the stable branch:
https://github.com/topology-tool-kit/ttk/blob/stable/examples/python/example.py

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by michalstepniewski** [comment]
ok :) will do that :) cheers :)
