### ISSUE TITLE
Issues getting started.

### ISSUE THREAD

**Issue by aewb** [topology-tool-kit/ttk#354]
**Describe the bug**
First, I'm not a programmer.  I am trying to get this tool/technology to investigate some data.

Using Conda, I followed the direction to install topologytoolkit. Please note I used a different name for the environment. 
When I try to run the example using ./example.py ../data/inputData.vtu
I get the following error:
OMP:Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Caution, outside GCC, sequential sort

**Expected behavior**
No idea, trying to see what happens. 

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. iOS]. macOS Mojave, version 10.14.6
 - Compiler [e.g. 22] - DON'T KNOW
 - Installed TTK's optional dependencies - followed the instructions for anaconda:
conda install -c conda-forge topologytoolkit 

**Additional context**
Again, not a programmer.  This may be something simple.  I read in the technical document, you want non programmers to be able to use this tool.  I am the perfect use-case. :)

**Comment by julien-tierny** [comment]
hi there,

thanks for your issue.

> First, I'm not a programmer.  I am trying to get this tool/technology to investigate some data.
if you want to try out ttk (with paraview) without installing it, you can also have a look at the pre-installed virtual machines (virtualbox images) that we provide for tutorials: http://sci.utah.edu/~jtierny/ttk.ova

we also provide docker images that are also easy to setup:
https://github.com/topology-tool-kit/ttk/tree/dev/scripts/docker

then, form there, you can follow directly our video tutorials with that setup (https://topology-tool-kit.github.io/tutorials.html).

> When I try to run the example using ./example.py ../data/inputData.vtu
> I get the following error:
> OMP:Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
> Caution, outside GCC, sequential sort
do you get any other output message?

> No idea, trying to see what happens. 
in principle, you should get a lot of ttk output messages (finishing on stats coming from the morse-smale complex module). also, the script is supposed to save in the current directory the output of the analysis (segmentation.vtu, separatrices.vtu, curve.vtk). do you have those files?

> OMP:Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
> Caution, outside GCC, sequential sort
@lhofmann
is that a known issue with the conda package for mac? should we disable openmp for those?
@macusers (@cgarth, @dsakurai0, @jalevine)
is this a known issue on mac?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by lhofmann** [comment]
Unfortunately, I don't have access to an OSX system, so I can't test it myself.
However, it seems that this is just a warning, which can simply be ignored.
I found this, which suggests, that there is no viable fix at the moment: https://syten.eu/docs/faq.html#faq_omp_nested

Also note, that the Python example has no visual output. Instructions on how to add output using the `pyvista` module can be found in this comment: https://github.com/topology-tool-kit/ttk/pull/263#issuecomment-527117692

**Comment by jalevine** [comment]
libomp has experimental support on MacOS, depending on what version one is
using.  The most recent installation instructions say that TTK will build
with it installed, but for ParaView we prefer TBB.

I've not tested the conda version though -- so perhaps through Conda it's
using a different build of libomp and it leads to the warning.

Josh

**Comment by aewb** [comment]
Thank you for your quick response.  I have downloaded the virtual machine.  I tried to open with VMWare version 10.  Please see attached screenshot.  It says "Operating System not found."

    On Wednesday, May 20, 2020, 04:39:54 AM CDT, Julien Tierny <notifications@github.com> wrote:  
 
 

hi there,

thanks for your issue.

> First, I'm not a programmer. I am trying to get this tool/technology to investigate some data.
if you want to try out ttk (with paraview) without installing it, you can also have a look at the pre-installed virtual machines (virtualbox images) that we provide for tutorials: http://sci.utah.edu/~jtierny/ttk.ova

we also provide docker images that are also easy to setup:
https://github.com/topology-tool-kit/ttk/tree/dev/scripts/docker

then, form there, you can follow directly our video tutorials with that setup (https://topology-tool-kit.github.io/tutorials.html).

> When I try to run the example using ./example.py ../data/inputData.vtu
> I get the following error:
> OMP:Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
> Caution, outside GCC, sequential sort
do you get any other output message?

> No idea, trying to see what happens. 
in principle, you should get a lot of ttk output messages (finishing on stats coming from the morse-smale complex module). also, the script is supposed to save in the current directory the output of the analysis (segmentation.vtu, separatrices.vtu, curve.vtk). do you have those files?

> OMP:Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
> Caution, outside GCC, sequential sort
@lhofmann
is that a known issue with the conda package for mac? should we disable openmp for those?
@macusers (@cgarth, @dsakurai0, @jalevine)
is this a known issue on mac?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
>  I have downloaded the virtual machine.  I tried to open with VMWare version 10.  Please see attached screenshot.  It says "Operating System not found."
these are virtualbox images. please use virtualbox.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi there,

I'm going to go ahead and close that one (as we haven't heard back from you). please feel free to re-open if you want to get back to it.

cheers,
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
