### ISSUE TITLE
[ExplicitTriangulation] Unsupported dimension for boundary preprocessing

### ISSUE THREAD

**Issue by mahdikooshkbaghi** [topology-tool-kit/ttk#358]
I can reproduce the `dragon.psvm` example. However, I made a toy point cloud (3-bolbs), computed the `Elevation` function and then try to do the persistent curve and the TTK crashes with the following error:
```bash
[Common] Welcome!
[OneSkeleton] Edge-list built in 0.000249147 s. (0 edges, 1 thread(s)).
[ZeroSkeleton] One-skeleton built in 0.000620842 s. (8 thread(s)).
[ExplicitTriangulation] Unsupported dimension for boundary preprocessing.
[FTM] ------------
[FTM] number of threads : 8
[FTM] * debug lvl  : 3
[FTM] * tree type  : Join + Split
[FTM] ------------
[FTM] alloc in           0.00196695
[FTM] init in            0.000203133
[FTM] sort step in       0.00276208
leafSearch in            0.00965905
double free or corruption (!prev)
```

Some information about the installation:
`paraview version 5.6.1`
`ttk version 0.9.8`
`Compiled from source on Linux`.

Here is the script to make the bolbs:
`paraview --script=bolbs.py`

and here is the content of bolbs.py

```python
from paraview.simple import *
programmableSource1 = ProgrammableSource()
programmableSource1.Script = """
import numpy as np
from sklearn.datasets.samples_generator import make_blobs
centers = [[1.56, 2.22, 0], [-1.743, -1, 1], [1.7, -2, -1]]
nbpts = 10000
X, _ = make_blobs(n_samples=nbpts, centers=centers, cluster_std=0.6)
output.Points = X
output.PointData.append(X[:,0], "x")
output.PointData.append(X[:,1], "y")
output.PointData.append(X[:,2], "z")
ptIds = vtk.vtkIdList()
ptIds.SetNumberOfIds(nbpts)
for a in range(nbpts):
    ptIds.SetId(a, a)
output.Allocate(1)
output.InsertNextCell(vtk.VTK_POLY_VERTEX, ptIds)
"""
```

**Comment by julien-tierny** [comment]
hi, 

you need to triangulate your point cloud before proceeding to further analysis. 
see the tutorial page of ttk (https://topology-tool-kit.github.io/tutorials.html), in particular:
* overview: https://youtu.be/5m5sZ3DFtmA?t=2603
* examples: https://topology-tool-kit.github.io/tutorials.html#high

I'm going to go ahead and close that issue.

if you're still running into issues, please continue this discussion on the user mailing list (ttk-users@googlegroups.com)

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
