### ISSUE TITLE
MatrixToHeatMap Paraview UI won't show RegExp edit line

### ISSUE THREAD

**Issue by hugo-manet** [topology-tool-kit/ttk#382]
When "Select Fields with a Regexp" is checked, the corresponding regexp doesn't show.

**To Reproduce**
1. Load a TTKMatrixToHeatMap in paraview
2. Check "Select Fields with a Regexp" in "Input Options"

**Expected behavior**
The "Regexp" line should appear, as suggested in the .XML file

**System (please complete the following information):**
 - OS: Ubuntu
 - Paraview Version 5.8.0
- TTK Version 0.9.9, dev branch

**Fix**
Remove `panel_visibility="advanced"` of the corresponding widget in the .XML file, line 76

**Comment by julien-tierny** [comment]
good catch.
can you PR the fix and mention that issue in the PR?

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
