### ISSUE TITLE
Tag name pattern (no v?)

### ISSUE THREAD

**Issue by dsakurai** [topology-tool-kit/ttk#416]
The v0.9.8 tag looks like the newest on Github because it is on top.
(I didn't notice 0.9.8.9 for half a year.)

See the screenshot:
<img width="309" alt="image" src="https://user-images.githubusercontent.com/16434308/86213849-46d41400-bbb5-11ea-89c6-798e4130014d.png">

No offense, but doesn't it make sense to create a tag named v0.9.8.9?

**Comment by julien-tierny** [comment]
good catch, thanks daisuke. the release has been edited accordingly.
