### ISSUE TITLE
Can ttkTriangulation keep a shared pointer to the input datasets?

### ISSUE THREAD

**Issue by jspanchu** [topology-tool-kit/ttk#449]
**The problem**
I am aware that ttkTriangulation exhibits unspecified behaviour if the input VTK objects go out of scope.
From what I understand, the problem occurs due to the dangling pointer `inputDataSet_` initialized as a raw pointer [here](https://github.com/topology-tool-kit/ttk/blob/76abae8a5ba78ffe59b78af81c59509bb3784499/core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.h#L152) and assigned [here](https://github.com/topology-tool-kit/ttk/blob/76abae8a5ba78ffe59b78af81c59509bb3784499/core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp#L343), [here](https://github.com/topology-tool-kit/ttk/blob/76abae8a5ba78ffe59b78af81c59509bb3784499/core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp#L434) and [here](https://github.com/topology-tool-kit/ttk/blob/76abae8a5ba78ffe59b78af81c59509bb3784499/core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp#L461)

If I set the input data for the ttkTriangulation within a scope.
```c++
{
    vtkSmartPointer<vtkUnstructuredGrid> uGrid = InterestingFilter->GetOutput();
    std::shared_ptr<ttkTriangulation> m_Triang = std::make_shared<ttkTriangulation>();
    m_Triang->setInputData(uGrid); // passed as vtkSmartPointer, but TTK takes in raw pointer! And stores it!
    m_Triang->getVtkUnstructuredGrid()->Print(std::cout); // Works fine :)
}
```
And in another scope, if I try to access the unstructured grid representation
```c++
{
    m_Triang->getVtkUnstructuredGrid()->Print(std::cout); // Fails :(
}
```
This throws an exception right in the very beginning of the function `vtkUnstructuredGrid *ttkTriangulation::getVtkUnstructuredGrid()` [here](https://github.com/topology-tool-kit/ttk/blob/76abae8a5ba78ffe59b78af81c59509bb3784499/core/vtk/ttkTriangulationAlgorithm/ttkTriangulation.cpp#L143).
```
Exception thrown: read access violation.
this->inputDataSet_->**** was 0xFFFFFFFFFFFFFF37.
```
This is not really an expected usage. I would want to get a vtkUnstructuredGrid representation of my `ttkTriangulation` at any instant of my program as long as the `ttkTriangulation` object is alive!

**A solution?**
Was there a rationale behind using a raw pointer for `inputDataset_`? I noticed that few other modules(`ttkTopologicalCompression*`) depend on `ttkTriangulation::setInputData()`. Besides, I see no reason why the memory footprint of `ttkTriangulation` would be affected by such modification (It's just reference counting). Since TTK already uses `std::shared_ptr` in other modules, either that or better a `vtkSmartPointer` can be incorporated. I feel it's better to stick to `vtkSmartPointer` for VTK datatypes.

If there is nothing obstructing this change, I think it should be implemented at least for safety purposes!

**Comment by julien-tierny** [comment]
hi there,

thanks for your message.

that's a good call.
why don't you PR the fix? (it's close to be a 1-liner)

(note that ttk's interface with vtk is currently being largely revamped. so ttkTriangulation should be marked deprecated soon)

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
this once is marked as obsolete as ttkTriangulation should no longer be available from the outside given the new api (with triangulation factory).
