### ISSUE TITLE
ParaView proxy names should have a ttk prefix

### ISSUE THREAD

**Issue by lhofmann** [topology-tool-kit/ttk#454]
Currently, all XML files contain declarations like this:
```xml
<SourceProxy name="ArrayEditor" class="ttkArrayEditor" label="TTK ArrayEditor">
```
Because proxy names are unique within ParaView, I have run into duplicate proxy names before, since I had similar naming schemes in my own code base. Especially the more generic ones like ArrayEditor, Extract, etc. could easily cause conflicts elsewhere.
These names are as far as I know only used internally in ParaView and in the state files. Since the pvpython interface uses the labels as Python class names, all pvpython scripts will be unaffected.

I propose to change all declarations such that the name is equal to the class name wherever possible:
```xml
<SourceProxy name="ttkArrayEditor" class="ttkArrayEditor" label="TTK ArrayEditor">
```
Compatibility with state files (especially those existing outside of ttk-data) could be maintained by adding aliases like this:
```xml
<SourceProxy base_proxygroup="filters"
             base_proxyname="ttkArrayEditor"
             class="ttkArrayEditor"
             name="ArrayEditor"
             label="TTK ArrayEditor (deprecated)">
    <Deprecated deprecated_in="5.8" to_remove_in="5.9">
        Please update your state file to use ttkArrayEditor instead of ArrayEditor.
    </Deprecated>
</SourceProxy> 
```
These will not appear in the filters menu, and a deprecation message is printed when used (e.g. loaded from an old state file).

**Comment by julien-tierny** [comment]
hi lutz, thanks a lot for the suggestion.

in principle I'm ok with it.
for ttk-data however, I'd run ```sed``` on them to make sure they use the new name (to avoid an explosion of warning/error messages on paraview startup).

could you PR both ttk and ttk-data in that line of thought?

cheers,
