### ISSUE TITLE
Problem building TTK dev branch with plugins

### ISSUE THREAD

**Issue by josiahblaisdell** [topology-tool-kit/ttk#476]
**Describe the bug**
I have patched and built Paraview 5.8. When I run cmake-gui and try to 'configure" I get a series of errors that it is looking for "TTKFilter.cmake" in various directories that do not have a ttkfilter.cmake.

I manually added an empty file called TTKFilter.cmake and this fixed the issue. I think the following lines need to be added to .../ttk/paraview/CMakeLists.txt at line 11
AND NOT ${PARAVIEW_PLUGIN} MATCHES "Remoting")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "VTKExtensions")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "Qt")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "lib")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "core")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "Clients")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "VTK")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "paraview")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "TTK")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "standalone")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "CMakeFiles")
AND NOT ${PARAVIEW_PLUGIN} MATCHES "ExternalData")

**To Reproduce**
I tried to remember everything I did... I think I included everything... Steps to reproduce the behavior:
1. Download paraview 5.8 source
2. Download ttk source
3. install all the pre-reqs
4. patch the paraview source
5. build paraview
6. build ttk

**Comment by CharlesGueunet** [comment]
Hello Josiah,

The folder that you excluded in the CMakeLists.txt are not in the TTK repository.
At first, it looks like these files come from ParaView. By chance, have you cloned ParaView inside TTK ?
If so, you may want to retry the installation process having your ParaView folder outside of the TTK repository to avoid this conflict.

**Comment by josiahblaisdell** [comment]
Hmm you are correct... The only way I could reproduce this was running the patch on the paraview directory in TTK rather than the paraview src tree directory. I think this must be what happened. I must have left out a ".." and just continued on and re-patched the paraview src tree and completely forgotten about it.
