### ISSUE TITLE
TTK + Python: Calls to ttkBottleneckDistance Getresult() return -1

### ISSUE THREAD

**Issue by josiahblaisdell** [topology-tool-kit/ttk#477]
**Fix**
I have fixed this in my own code. I just passed the result by reference into the computeDistance() function and set the value to the distance. 

**Describe the bug**
I created 2 persistence diagrams and passed both of these diagrams and used the ttkBottleneckDistance() to compute the distance between the persistence diagrams. There is a member variable "result" and a vtk macro to get the result in ttkBottleneckDistance.h. After computing the bottleneck distance between two persistence diagrams this "result" is still -1. Not the result of the bottleneck distance algorithm 

**To Reproduce**
```
    #1. Get the names of the variables in the MRI data
    name1 = vtk1.GetScalarsNameInFile(0)
    name2 = vtk2.GetScalarsNameInFile(0)

    #2. threshold fata greater than 0
    e1_threshold = vtkThreshold()
    e1_threshold.SetInputConnection(vtk1.GetOutputPort())
    e1_threshold.SetInputArrayToProcess(0,0,0,0,name1)
    e1_threshold.ThresholdBetween(0.1, 999999)
    e1_threshold.Update()
    pdb.set_trace()

    #3. Tetrahedralize the data in order to create persistence diagram
    tet1 = vtkDataSetTriangleFilter()
    tet1.SetInputConnection(e1_threshold.GetOutputPort())
    tet1.SetInputArrayToProcess(0,0,0,0,name1)
    tet1.Update()

    #4. Create the persistence diagram
    persistence_dgm1 = ttkPersistenceDiagram()
    persistence_dgm1.SetInputConnection(tet1.GetOutputPort())
    persistence_dgm1.SetInputArrayToProcess(0,0,0,0,name1)
    persistence_dgm1.Update()

    #5. Threshold out the persistence diagram main diagonal
    threshold1 = vtkThreshold()
    threshold1.SetInputConnection(persistence_dgm1.GetOutputPort())
    threshold1.SetInputArrayToProcess(0,0,0,vtkDataObject.FIELD_ASSOCIATION_CELLS,'Persistence')
    threshold1.ThresholdBetween(.01,9999999)
    threshold1.Update()

    #6 Threshold the data greater than 0
    e2_threshold = vtkThreshold()
    e2_threshold.SetInputConnection(vtk2.GetOutputPort())
    e2_threshold.SetInputArrayToProcess(0,0,0,0,name2)
    e2_threshold.ThresholdBetween(0.1, 999999)
    e2_threshold.Update()

    #7. Tetrahedralize the second dataset
    tet2 = vtkDataSetTriangleFilter()
    tet2.SetInputConnection(e2_threshold.GetOutputPort())
    tet2.SetInputArrayToProcess(0,0,0,0,name2)
    tet2.Update()

    #8. Create the second persistence diagram using thresholded data
    persistence_dgm2 = ttkPersistenceDiagram()
    persistence_dgm2.SetInputConnection(tet2.GetOutputPort())
    persistence_dgm2.SetInputArrayToProcess(0,0,0,0,name2)
    persistence_dgm2.Update()

    #9. Threshold the persistence of second diagram
    threshold2 = vtkThreshold()
    threshold2.SetInputConnection(persistence_dgm2.GetOutputPort())
    threshold2.SetInputArrayToProcess(0,0,0,vtkDataObject.FIELD_ASSOCIATION_CELLS,'Persistence')
    threshold2.ThresholdBetween(.01,99999999999)
    threshold2.Update()
    
    #10. Compute the persistence diagram matrix
    persistence_dgm_dist = ttkBottleneckDistance()
    persistence_dgm_dist.SetDistanceAlgorithm('ttk')
    persistence_dgm_dist.SetWassersteinMetric('2')
    persistence_dgm_dist.SetInputConnection(0,threshold1.GetOutputPort())
    persistence_dgm_dist.SetInputArrayToProcess(0,0,0,vtkDataObject.FIELD_ASSOCIATION_CELLS,'Persistence')
    persistence_dgm_dist.SetInputConnection(1,threshold2.GetOutputPort())
    persistence_dgm_dist.SetInputArrayToProcess(0,0,0,vtkDataObject.FIELD_ASSOCIATION_CELLS,'Persistence')
    persistence_dgm_dist.SetInputDataObject(0,threshold1.GetOutput())
    persistence_dgm_dist.SetInputDataObject(1,threshold2.GetOutput())
    persistence_dgm_dist.Update()
    
    #11. HERE IS WHERE THE BUG OCCURS -- this call "Getresult()" returns -1
    distance = persistence_dgm_dist.Getresult()

```
**Expected behavior**
The call to distance result returns the actual distance.

**System (please complete the following information):**
 - OS: Ubuntu 18.04 
 - Compiler: Python 3.7
 - Installed TTK's optional dependencies

From cmake:
-- GraphViz found
-- Found SQLITE3: /usr/lib/x86_64-linux-gnu/libsqlite3.so
-- Python version: 3.7
-- Numpy headers: /usr/include
-- ttk options -----------------------------------------------------------------
-- TTK_ENABLE_64BIT_IDS: OFF
-- TTK_ENABLE_CPU_OPTIMIZATION: ON
-- TTK_ENABLE_DOUBLE_TEMPLATING: OFF
-- TTK_ENABLE_EIGEN: ON
-- TTK_ENABLE_GRAPHVIZ: ON
-- TTK_ENABLE_KAMIKAZE: ON
-- TTK_ENABLE_MPI: OFF
-- TTK_ENABLE_OPENMP: ON
-- TTK_ENABLE_SCIKIT_LEARN: ON
-- TTK_ENABLE_SPECTRA: ON
-- TTK_ENABLE_SQLITE3: ON
-- TTK_ENABLE_ZFP: ON
-- TTK_ENABLE_ZLIB: ON
-- ttk build -------------------------------------------------------------------
-- CMAKE_BUILD_TYPE: RELEASE
-- TTK_BUILD_DOCUMENTATION: OFF
-- TTK_BUILD_PARAVIEW_PLUGINS: ON
--   ParaView_DIR: /usr/local/lib/cmake/paraview-5.8
-- TTK_BUILD_STANDALONE_APPS: OFF
-- TTK_BUILD_VTK_WRAPPERS: OFF
-- ttk install -----------------------------------------------------------------
-- CMAKE_INSTALL_PREFIX: /usr/local
-- TTK_PYTHON_MODULE_DIR: 
-- TTK_INSTALL_PLUGIN_DIR: /usr/local/lib/cmake/paraview-5.8/../../../bin/plugins

**Additional context**

**Comment by josiahblaisdell** [comment]
Hi there @pierre-guillou , 

I have tested the changes you merged three days ago, I now see that you are setting "result" to the status of the bottleneck algorithm, but this also isn't what I think you intended result to be. The member variable result is declared to be a double, presumably it was intended that result would store the distance between the persistence diagram. I am seeing that even when writing a ttk+vtk C++ standalone app the getDistance() function is inaccessible. There should be a function to get the computed bottleneck distance right?

Really quick 1 line fix: in ttkBottleneckDistance.h change derivation "protected ttk::BottleneckDistance" to "public ttk::BottleneckDistance". The getDistance() function is accessible with this one change.

Thanks,
Josiah

**Comment by pierre-guillou** [comment]
Hi Josiah,

Sorry for this inconvenience, I think I misunderstood your problem here. In fact, what I fixed was the return value of the `RequestData` method, which after our big architectural changes of this summer should be 1 in case of success and 0 (or something != 1) in case of failure (leading to VTK warnings). I wrongfully though it was linked to the problem here.

In fact, while looking at it now, it seems that the variable `result` is not used in the BottleneckDistance module. The variable is set in the constructor to -1 and is never touched afterwards, which corresponds to your issue here. Looking to the base layer, I think the `result` class member should hold the value of (or be replaced with) the `distance_` class member in core/base/bottleneckDistance/BottleneckDistance.h. Do you think this approach could solve this issue?

I'll make these changes and propose them in a further PR.

Pierre

**Comment by josiahblaisdell** [comment]
Yes this will solve the issue, it will also make it work in python+ttk.

**Comment by josiahblaisdell** [comment]
This is working now, thank you!
