### ISSUE TITLE
Randomizers should be deterministic

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#499]
I know it sounds strange at first, but I would actually suggest to make the randomization procedures (for example of IdentifierRandomizer) deterministic for a given seed. By varying the seed parameter we get randomness, with the additional advantage that if set once the output stays consistent.

**Comment by CharlesGueunet** [comment]
+1, that would also be useful if we want to generate test that make use of these filters. That is what we do in VTK for instance.

**Comment by julien-tierny** [comment]
I'm on board too, thanks for PR'ing IdentifierRandomizer when you have a second.
cheers,
