### ISSUE TITLE
TTK's cmd and gui programs do not build on Gentoo

### ISSUE THREAD

**Issue by pavolzetor** [topology-tool-kit/ttk#5]
I followed all steps in the installation guide with small twist as I enabled `withVTKCMD` and `withVTKGUI`.
[CMakeCache.txt](https://github.com/topology-tool-kit/ttk/files/903643/CMakeCache.txt)

Note, I am building with option `withParaView` enabled, which is checked on line 319 in `core/ttk.cmake`.

**Comment by julien-tierny** [comment]
pavol,
thanks for your feedback.

from your explanation, it seems that you did not follow the installation procedure properly.
I can only invite you to respect installation instructions in general, with no "small twist".

as explained in the installation instructions, by default all TTK components (ParaView plugins, command line tools and VTK-based GUIs) will be built and installed. there's nothing more to do to trigger command-line support.
if you wish to disable the build and install of certain TTK components, just comment the corresponding line in the CMakeLists.txt at the root of the source tree. I clarified the installation instructions in that regard.

I will therefore close your issue and pull requests on the principle that there's no need to fix something that's not broken.

regarding the three variables you mention, these are internal, purposefully non-documented variables. you should not modify their value unless you really understand how they are used by the rest of TTK's build.

finally, although we don't advertise it much, if you look carefully, you'll see that TTK ships with overlay ebuilds that will make gentoo users' life easier. these automatically install the TTK-patched version of ParaView. I refer you to the gentoo documentation to see how to include them as a local overlay of your portage tree.

**Comment by julien-tierny** [comment]
hi pavol,
for your information, this inconvenience has now been fixed.

**Comment by pavolzetor** [comment]
Thanks Julien
