### ISSUE TITLE
Unnecessary implicit preconditioning

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#500]
**Describe the bug**
When chaining filters in paraview on a regular grid, the implicit preconditioning happens at each filter. In previous versions, that preconditioning took virtually no time, now it does

**To Reproduce**
1. Load a regular grid
2. Apply a scalar field smoother 1 (max debug level)
3. Apply a scalar field smoother 2 (max debug level)
4. Apply a scalar field smoother 3 (max debug level)
In the console, the line ```Apply a scalar field smoother 2 (max debug level)``` occurs 3 times

**Expected behavior**
The preconditioning should happen only once and only 1 triangulation should be registered.

**Screenshots**
![implicitPreconditioning](https://user-images.githubusercontent.com/3018628/94549699-e788ad00-0252-11eb-958c-127a8daada6c.png)

**System (please complete the following information):**
 - OS: gentoo linux
 - Compiler gcc 9.3
 - Installed TTK's optional dependencies all

**Additional context**
@JonasLukasczyk 
I didn't have time to further look into this but that'd be great if we come up with a fix before the release.

cheers

**Comment by pierre-guillou** [comment]
Seems that `ttk::AbstractTriangulation::hasPreconditionedVertexNeighbors_` should be tested in `ttk::AbstractTriangulation::preconditionVertexNeighbors()` before calling the internal method.

**Comment by julien-tierny** [comment]
actually, I think the issue rather comes from the number of registered triangulations which should be 1 instead of 3 (see debug messages)

**Comment by pierre-guillou** [comment]
You are right, one triangulation object is generated per filter (instead of modifying the same triangulation object in the pipeline).

**Comment by julien-tierny** [comment]
alright, looks good to me!
cheers,
