### ISSUE TITLE
TTK objects does not seem to have GetOutput() attribute.

### ISSUE THREAD

**Issue by farhanone** [topology-tool-kit/ttk#544]
TTK filters does not seems to have GetOuput() function. However, GetOutputPort() is working as it should be. GetOutput() function for VTK is working fine. Both TTK and VTK are interacting (passing outputs by GetOutputPort()) with eachother flawlessly.

**To Reproduce**
```
import vtk
import topologytoolkit as ttk
inputFilePath = "../TTK/ttk/examples/data/inputData.vtu"
reader = vtk.vtkXMLUnstructuredGridReader()
reader.SetFileName(inputFilePath)
reader.Update()
try:
    reader.GetOutput()
except:
    print("GetOutput() is not working for VTK filters")
diagram = ttk.ttkPersistenceDiagram()
diagram.SetInputConnection(reader.GetOutputPort())
diagram.SetInputArrayToProcess(0, 0, 0, 0, "data")
diagram.SetDebugLevel(3)
try:
    diagram.GetOutputPort()
except:
    print("GetOutputPort() is not working for TTK filters")
try:
    diagram.GetOutput()
except:
    print("GetOutput() is not working for TTK filters")

diagram.GetOutput() # Error at this place
```

**Expected behavior**
Should output the data by GetOutput().

**System**
 - Ubuntu 20.04
 - python3.8
 - I don't think optional dependencies are cause of it.

**Error**
```
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    diagram.GetOutput()
AttributeError: 'topologytoolkit.ttkPersistenceDiagram.ttkPersisten' object has no attribute 'GetOutput'
```
**NOTE**
I am on latest **dev** branch. I have build the TTK with Paraview5.8.0. TTK version 0.9.9 is shown on paraview.

**Comment by lhofmann** [comment]
You can use `GetOutputDataObject(0)` instead.

`GetOutput` is a convenience method implemented by `vtkDataSetAlgorithm`, which was the VTK base class for TTK filters up to version 0.9.8.9. It should probably be reintroduced to the new `ttkAlgorithm` base class.

**Comment by farhanone** [comment]
Great! 
Thanks @lhofmann. It works as same as GetOutput(). 
I am closing this issur.
