### ISSUE TITLE
regression on `nestedTrackingGraph.pvsm` and `trackingFromOverlap.pvsm`

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#559]
**Describe the bug**
the above state files report empty output while they should not.

**To Reproduce**
```
paraview states/nestedTrackingGraph.pvsm
```

``
paraview states/trackingFromOverlap.pvsm
``

**Expected behavior**
the state files report empty render views.
note that the z coordinates of the objects being rendered is completely off (10^23).
this might be the issue. 

**Screenshots**
![Screenshot_20210201_093602](https://user-images.githubusercontent.com/3018628/106434078-5a0fd080-6471-11eb-81cf-c9b5fb11c3ce.png)
![Screenshot_20210201_093655](https://user-images.githubusercontent.com/3018628/106434170-7875cc00-6471-11eb-9add-b632b47fd28b.png)

**System (please complete the following information):**
 - OS: [e.g. iOS] gentoo 
 - Compiler [e.g. 22] gcc 9
 - Installed TTK's optional dependencies all

**Additional context**
the problem with the z coordinate may have been there before and not so much of an issue with paraview 5.8. 
this regression has been observed with paraview 5.9 (maybe that version is more sensible to this depth inconsistency)

@pierre-guillou 
can you confirm you can reproduce?
were you using paraview 5.9 already in #558 (you reported no issue with the state files back then).
thanks for your feedback.

**Comment by pierre-guillou** [comment]
I indeed experimented this issue several days ago with ParaView 5.9(-RC2). I went back to ParaView 5.8 and it disappeared. When still on ParaView 5.9, I tried to bisect the issue but it seemed already there in the TTK dev branch and not introduced by my recent changes.

**Comment by julien-tierny** [comment]
alright, thanks pierre!
@JonasLukasczyk 
it seems that some of your modules are having issues with paraview 5.9 (which has been released a few days ago). 
do you think you could have a look into this?
cheers,

**Comment by JonasLukasczyk** [comment]
Hi everyone,
I checked and the problem is in the MeshGraph module. I will have a closer look and upload a fix soon.

Best
Jonas

**Comment by pierre-guillou** [comment]
There is also a similar issue arising in `uncertainStartingVortex.pvsm`: some layers seems to have been permuted.

With ParaView 5.8.1
![pv5 8](https://user-images.githubusercontent.com/47317188/106630425-1e156200-657c-11eb-9a48-c7d2078b1d05.png)

With ParaView 5.9.0 (the release, not the RC)
![pv5 9](https://user-images.githubusercontent.com/47317188/106630500-2e2d4180-657c-11eb-8e2b-97fa13d14470.png)

**Comment by julien-tierny** [comment]
the commit ttk-data/d848939 should have fixed it.
is your local repo in sync?

**Comment by pierre-guillou** [comment]
I indeed missed that commit. The state runs fine with it. My bad.
Sorry for the inconvenience.

**Comment by julien-tierny** [comment]
no worries :) 
(I prefer double checks)

**Comment by JonasLukasczyk** [comment]
Hi all,
I opened a PR that solves the issue. The core problem was that the MeshGraph module used the old connectivity array layout and that it only supported floating point coordinates. It seems that since PV 5.9 some filters produce double point coordinates by default, which caused incorrect casts.

Best
Jonas

**Comment by julien-tierny** [comment]
fixed with PR #561
