### ISSUE TITLE
FTMTree - Segmentation Arrays broken

### ISSUE THREAD

**Issue by floWetzels** [topology-tool-kit/ttk#570]
Hi,
@JonasLukasczyk and I found some weird behaviour in the FTMTree filter, which we would consider a bug.

**Describe the bug**
The segmentation output of FTMTree has point data arrays "SegmentationId" and "RegionSize" along with others. In Paraview, it does not have any cell data arrays attached (see Screenshot below). However, when printing the vtk object from the C++ layer, the two arrays "SegmentationId" and "RegionSize" exist as cell data and point data (screenshot of output attached as well). While trying to find the problem, Jonas and I removed lines 187 to 192 from the ttkFTMTree.cpp, so the output should only be a shallow copy of the input. But there was still a point data array "ttkVertexScalarField" added. This seems to be a violation of the pipeline paradigm.
(@CharlesGueunet )

**To Reproduce**
You need some other (maybe C++) filter applied after FTMTree on the segmentation, which prints its input vtk object. For the pipeline violation, it should (hopefully) be enough to run FTMTree with the described changes on any input.

**System:**
 - OS: macos 11.2.1
 - Compiler GCC 9.3.0
 - TTK dev branch on my fork, currently 10 commits behind.

**Screenshots**
![Screenshot 2021-02-24 at 11 00 44](https://user-images.githubusercontent.com/36967183/108986776-c9ed3180-7692-11eb-89dd-d5ae08d8e19d.png)
<img width="422" alt="Screenshot 2021-02-24 at 11 07 04" src="https://user-images.githubusercontent.com/36967183/108986791-cf4a7c00-7692-11eb-90be-7e6aceaf6ef4.png">

**Comment by JonasLukasczyk** [comment]
@CharlesGueunet any thoughts on this?

**Comment by CharlesGueunet** [comment]
Yep, that is true. The call to `indentify`
https://github.com/topology-tool-kit/ttk/blob/591c27277e60f7a6da4c7cceacaa13a20a953108/core/vtk/ttkFTMTree/ttkFTMTree.cpp#L79

add an array to the input, which is not correct in the VTK pipeline.
