### ISSUE TITLE
Header-Only Base Code

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#573]
Hi all,
I have a lot of base code modules that contain an empty cpp file just because our current build system requires this, but of course it would be nicer if we could just skip these files right away. Does anyone know how complicated it would be to change our cmake code to make this work?

Best
Jonas

**Comment by lhofmann** [comment]
If I'm not mistaken, you can add header-only libraries using `ttk_add_base_template_library`.

**Comment by JonasLukasczyk** [comment]
Thanks @lhofmann! Refactoring PR incoming ;-)
