### ISSUE TITLE
Wrong indexing in BarycentricSubdivision.

### ISSUE THREAD

**Issue by unclejimbo** [topology-tool-kit/ttk#576]
**Describe the bug**
I think there is a bug in the indexing, which should be `i*3+0` etc.
https://github.com/topology-tool-kit/ttk/blob/9db2fe6c507dd4967a1807a1608d78b9ba2ff896/core/base/barycentricSubdivision/BarycentricSubdivision.h#L220-L225

**System (please complete the following information):**
 - OS: Archlinux
 - Compiler: gcc 10
 - Installed TTK's optional dependencies

**Comment by pierre-guillou** [comment]
Thanks for the bug report! (and the fix suggestion). You're right, the mesh generated by the BarycentricSubdivision module was broken. Seems that I did not test the module properly last time I modified it, sorry…
