### ISSUE TITLE
Build fails on Debian 10 using cmake 3.13.4

### ISSUE THREAD

**Issue by orting** [topology-tool-kit/ttk#583]
**Describe the bug**
The default cmake version on Debian 10 is 3.13.4 which fails to build ttk with a bunch of 
"Install TARGETS given no LIBRARY DESTINATION for shared library target ..."
errors.
cmake version 3.19.6 works.

CMakeLists.txt has `cmake_minimum_required(VERSION 3.12.2)` which probably needs to be updated.

**Comment by julien-tierny** [comment]
the current minimum required version is 3.14 (dev branch). thanks!
