### ISSUE TITLE
Alexander knot invariant not working for examples

### ISSUE THREAD

**Issue by raghavsreeram21** [topology-tool-kit/ttk#594]
The Alexander knot invariant function does not work for many of the example .xyz files. 

 Working for
'../data/1ax8.xyz'
 '../data/knot31.xyz' - shows some unkown or too many crossings
 '../data/knot52.xyz' - shows some unkown or too many crossings

 Not Working for
'../data/arc.xyz'
 '../data/arc1.xyz'
 '../data/arc2.xyz'
'../data/knot31.xyz'
 '../data/lasso.xyz'

**Error for arc.xyz **
Traceback (most recent call last):
  File "topoly_setup.py", line 24, in <module>
    runAlexnderOnGivenXYZFile(polygon, "png", "1ax8knotpdf")
  File "topoly_setup.py", line 16, in runAlexnderOnGivenXYZFile
    map_fileformat = outputType, map_filename = ("../data/" + outputFilename))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/topoly/__init__.py", line 176, in alexander
    run_parallel=run_parallel, parallel_workers=parallel_workers, debug=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/topoly/invariants.py", line 166, in calculate
    palette=palette, arrows=arrows, knot=knot, debug=debug)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/topoly/manipulation.py", line 233, in plot_matrix
    raise TopolyException("Nothing to draw. Cowardly refuses to draw empty matrix.")
topoly.params.TopolyException: Nothing to draw. Cowardly refuses to draw empty matrix.

**To Reproduce**
`def runAlexnderOnGivenXYZFile(inputFile:str, outputType:str, outputFilename:str):
    knot_matrix = alexander(polygon, closure=2, tries=10, matrix=True, matrix_density=1, 
                    matrix_calc_cutoff=0, matrix_map=True, 
                    map_fileformat = outputType, map_filename = ("../data/" + outputFilename))
    print('\n resulting knot matrix:\n', knot_matrix)
    return knot_matrix

if __name__ == "__main__":
    print("here first")
    polygon='../data/1ax8.xyz'
    runAlexnderOnGivenXYZFile(polygon, "png", "1ax8knotpdf")`

**Expected behavior**
Expected Alexander polynomial for given structure

**Comment by julien-tierny** [comment]
hi there,

thanks for your issue but unless I'm mistaken, I'm afraid your issue is not related to the topology tool kit (http://topology-tool-kit.github.io/). you may have wanted to post that issue for another project.

best,
