### ISSUE TITLE
[Question] Can ttk measure difference between Reeb graphs?

### ISSUE THREAD

**Issue by unclejimbo** [topology-tool-kit/ttk#596]
Hi, ttk community! Thanks for the great work.

Is there any class/function to measure distances between Reeb graphs?

**Comment by julien-tierny** [comment]
hi there, thanks for your message.
unfortunately, there's nothing implemented so far for Reeb graph comparison (if you'd like to contribute something, you're more than welcome). the closest you'll get is the matching/distance/clustering of persistence diagrams, as illustrated there:
https://topology-tool-kit.github.io/tutorials.html#ensemble

I hope this helps. cheers

**Comment by unclejimbo** [comment]
@julien-tierny Thanks for your advice. I'll try to contribute IF I get something working ;)
