### ISSUE TITLE
Examples should demand less powerful machine

### ISSUE THREAD

**Issue by pavolzetor** [topology-tool-kit/ttk#6]
Bivariate (out of memory) and uncertainty (overdraw resets GPU) examples crash on my modest laptop (4GB RAM). Potentially downscaling the datasets may help.

**Comment by julien-tierny** [comment]
pavol,
thanks for your feedback.

you're right regarding the second builtin example. we will down-sample it for the release of the next snapshot (0.9.1) where ParaView 5.3 will also be supported (hopefully in a few days from now).
I leave your issue open until then.

for the third builtin example, I'm not sure if there's anything easy we can do at the moment, except from asking valerio to buy you a new laptop :)

**Comment by julien-tierny** [comment]
hey, fyi, just down-sampling the input requires to re-do the user strokes (and thus the entire demo altogether). this might wait until we need to re-do that demo completely.
