### ISSUE TITLE
ParaView Layer CMake Cleanup

### ISSUE THREAD

**Issue by JonasLukasczyk** [topology-tool-kit/ttk#619]
Hi all,
in the PV layer we basically have per filter "always" two files, for example:
CinemaProductReader.xml
TTKFilter.cmake

but the TTKFilter.cmake seems to be superfluous since its content (`ttk_register_pv_filter(ttkCinemaProductReader CinemaProductReader.xml)`) could be generated automatically based on the folder/xml name. I realize there are some folders that do not have an xml file, in which case the content is reduced to `ttk_register_pv_filter(ttkUserInterfaceBase "")`, which can also be generated automatically.

My suggestion is to get rid of all these TTKFilter.cmake files and handle that automatically in cmake. We could even get rid of the folders and just list all xml files directly in the paraview folder.

In my opinion this would cleanup the code base. Any thoughts on this?

**Comment by julien-tierny** [comment]
simpler looks better :)
@CharlesGueunet: what do you think?

PS: `ttk_register_pv_filter(ttkUserInterfaceBase "")` looks like a hiccup (`ttkUserInterfaceBase` has nothing to do with paraview plugins)

**Comment by CharlesGueunet** [comment]
agreed, and having a collection of xml instead of the actual folder hierarchy seems really cool.

We will need to be careful how to process ttk modules with no ParaView counterpart (like containers or utilities for example)

**Comment by JonasLukasczyk** [comment]
This issue is resolved with PR #624
