### ISSUE TITLE
TTK without VTK dependency

### ISSUE THREAD

**Issue by ResearchDaniel** [topology-tool-kit/ttk#62]
Just got started on compiling TTK so I must admit that I have not looked too much into the code. Wondering if there is any chance that there will be a version C++ only version without a dependency on VTK?
Is it already possible to disable the parts using VTK?

**Comment by julien-tierny** [comment]
hi Daniel,

thanks for your message.

> version C++ only version without a dependency on VTK? Is it already
> possible to disable the parts using VTK?
yes, if you're using the current master branch of TTK's github repository, 
then you want to set the following cmake flags to OFF:
TTK_BUILD_PARAVIEW_PLUGINS=OFF
TTK_BUILD_STANDALONE_APPS=OFF
TTK_BUILD_VTK_WRAPPERS=OFF

this will build the C++-only layer of TTK (as static libraries).

the following example shows how to use the C++-only layer of TTK from your own 
code:
https://github.com/topology-tool-kit/ttk/tree/master/examples/c++

thanks for letting us know if you run into any issue.
cheers
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universites UPMC - LIP6
http://lip6.fr/Julien.Tierny
