### ISSUE TITLE
Win MSVC  build ? 

### ISSUE THREAD

**Issue by mv740** [topology-tool-kit/ttk#63]
Hi, 

is it possible to build this on windows using visual studio 2017? 
Using your latest commit, I am having some problems... 

error _isnan : is not a member of std; 

I have set Paraview_DIR & VTK_DIR.  I have no problem building ParaView. Do I need to add something more for a window build? I based by cmake configuration on your travis build.

**Comment by julien-tierny** [comment]
Dear Michal,

thanks a lot for your message.

> is it possible to build this on windows using visual studio 2017?
currently TTK is not officially supported under windows.
as a matter of fact, we're actively looking for a windows maintainer. 
if you were to have some time to spare and if you were willing to give a hand 
on this, that would be greatly appreciated and valued by end users I think.

that being said, with the latest cmake structure of TTK, things should be much 
simpler when it comes to porting TTK to windows.
in principle, we're only using standard C++11. so except a few minor edits 
here and there (like the one you pointed out), the port should not be very 
difficult.

thanks for letting us know if you'd be interested in giving a hand on this.

cheers,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universites UPMC - LIP6
http://lip6.fr/Julien.Tierny
