### ISSUE TITLE
Broken embedded diagrams (e.g. ttk-data/states/mergeTreeClustering.pvsm)

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#764]
This is a reminder (@pierre-guillou , @MatPont )

**Comment by pierre-guillou** [comment]
https://github.com/topology-tool-kit/ttk-data/pull/117 should do the trick

**Comment by pierre-guillou** [comment]
This has also a broader impact on the screenshots CI (the threshold seems to be too lax). Further PRs will fix that.
