### ISSUE TITLE
RankArray strange behavior on MPI branch

### ISSUE THREAD

**Issue by eve-le-guillou** [topology-tool-kit/ttk#783]
Hi all,

Some points have a wrong RankArray value. This only happens sometimes, not always, maybe 1 in 20 iterations. Adding an output of the RankArray array inside the RequestData function of the TTKGhostCellPreconditioning filter makes the problem disappear. I have noticed that the problem happens for the points with the following global ids: 32640, 32639, 32897, however it may happen for more points, I don't know.

**To Reproduce**

1. Add a small snippet of code in order to see the behavior. The should be added in the file ttkScalarFieldCriticalPoints.cpp ligne 72, in the function RequestData:

          long int *globalIds2 = triangulation->getGlobalIdsArray();
          rankArray_ = triangulation->getRankArray();
          for (int i = 0; i< triangulation->getNumberOfVertices(); i++){
              if (globalIds2[i] == 32640 || globalIds2[i]== 32639 || globalIds2[i]==32897){
              printErr("Element "+std::to_string(globalIds2[i])+ " possessed with RankArray: "+std::to_string(rankArray_[i]));
            }
          }
2. Compile TTK again.

3. Retrieve the ctBones.vti data available in ttk-data: [https://github.com/topology-tool-kit/ttk-data/blob/dev/ctBones.vti](url)
4. Apply the following pipeline in sequential, without MPI:

        #### import the simple module from the paraview
        from paraview.simple import *
        
        # create a new 'XML Image Data Reader'
        ctBonesvti = XMLImageDataReader(registrationName='ctBones.vti', FileName=['ctBones.vti'])
        ctBonesvti.PointArrayStatus = ['Scalars_']
        ctBonesvti.TimeArray = 'None'
        
        # create a new 'TTK ArrayPreconditioning'
        tTKArrayPreconditioning1 = TTKArrayPreconditioning(registrationName='TTKArrayPreconditioning1', Input=ctBonesvti)
        tTKArrayPreconditioning1.PointDataArrays = ['Scalars_']
        
        # create a new 'Generate Global Ids'
        generateGlobalIds1 = GenerateGlobalIds(registrationName='GenerateGlobalIds1', Input=tTKArrayPreconditioning1)
        
        SaveData("ctBones_prepared.pvd",generateGlobalIds1)

5. Now, run in parallel, using the following command:

      OMPI_MPI_THREAD_LEVEL=3 OMP_PLACES=cores OMP_PROC_BIND=close OMP_NUM_THREADS=4 mpirun -n 8 pvbatch pipeline.py

The pipeline:

        #### import the simple module from the paraview
        from paraview.simple import *
        data = PVDReader(registrationName='ctBones_prepared.pvd', FileName='/home/eveleguillou/experiment/IntegralLines/Correctness/MeSU/ctBones_prepared.pvd')
        data.CellArrays = ['GlobalCellIds']
        data.PointArrays = ['Scalars_', 'Scalars__Order', 'GlobalPointIds', 'vtkGhostType']
        
        # create a new 'Ghost Cells Generator'
        ghostCellsGenerator1 = GhostCellsGenerator(registrationName='GhostCellsGenerator1', Input=data)
        ghostCellsGenerator1.MinimumNumberOfGhosts = 2
        
        tTKGhostCellPreconditioning1 = TTKGhostCellPreconditioning(registrationName='TTKGhostCellPreconditioning1', Input=ghostCellsGenerator1)
        
        #tTKBlankFilter1 = TTKBlankFilter(registrationName='TTKBlankFilter1', Input=tTKGhostCellPreconditioning1)
        #tTKBlankFilter1.InputArray = ['POINTS', 'Scalars_']
        
        # create a new 'TTK ScalarFieldCriticalPoints'
        tTKScalarFieldCriticalPoints1 = TTKScalarFieldCriticalPoints(registrationName='TTKScalarFieldCriticalPoints1', Input=tTKGhostCellPreconditioning1)
        tTKScalarFieldCriticalPoints1.ScalarField = ['POINTS', 'Scalars_']
        tTKScalarFieldCriticalPoints1.InputOffsetField = ['POINTS', 'RankArray']
        tTKScalarFieldCriticalPoints1.Backend = 'Default generic backend'
        
        SaveData("CriticalPoints.pvtp", tTKScalarFieldCriticalPoints1)

**Expected behavior**
The normal behavior would be that all points belong to the same process, therefore RankArray should have the same value on all processes (3 for me on my machine). However, sometimes, the value on process 0 will be 0 as can be seen in the screenshot below.

**Screenshots**

![image](https://user-images.githubusercontent.com/36100726/171649246-fa227598-afc7-4bdd-9de0-dbe83da92bbe.png)

**System :**
 - OS: Ubuntu 20.04.4 LTS
- Compiler : GCC 10.3.0
- MPI implementation: Open MPI 4.0.3
 - TTK compiled with TTK_ENABLE_MPI and TTK_ENABLE_MPI_TIME to ON
 - Paraview: 5.10.1

**Additional context**
I don't believe the problem comes from ScalarFieldCriticalPoints, as the values of RankArray are incorrect before the execution of the filter. However, placing a print at the end of the TTKGhostPreconditioning filter makes the problem disappear, which is why I added the ScalarFieldCriticalPoints. @m-s-will any idea where this could be coming from?

I am available if any additional piece of information is needed.

Thank you for any help,

Eve Le Guillou

**Comment by m-s-will** [comment]
Hmm that is indeed weird, because apparently it gets the information from rank 0, otherwise there would be garbage data in there. Does it always shop up as rank 0? What do these globalids report on their vtkGhostType e.g. in spreadsheet view? I will look further into it tomorrow.

**Comment by eve-le-guillou** [comment]
Thank you for your reponse.

Yes, it does always show up as rank 0. I haven't been able to reproduce the problem when executing the pipeline in the graphical interface, so I don't know what value has the vtkGhostType in the Spreadsheet view. It can probably be accessed from within TTK, though.

**Comment by m-s-will** [comment]
I also am not able to reproduce the problem in the Paraview UI and for some reason the `pipeline.py` does not run on my setup, `pvbatch` says that `TTKGhostCellPreconditioning` is undefined even though the python module and the TTK VTK wrappers should be built and I can find it by using:
```
import topologytoolkit
ghostCellPrecond = topologytoolkit.ttkGhostCellPreconditioning()
```
Is there something separate that needs to be done so I can use it with `import paraview.simple`?

**Comment by eve-le-guillou** [comment]
Indeed, I forgot to add `from paraview.simple import *` at the beginning of the second pipeline. I don't see anything else needed to execute the Pipeline. I compiled TTK on my machine using the following tutorial: [https://topology-tool-kit.github.io/installation-linux-sources.html](url). 
I didn't change any of the default path variables.

**Comment by m-s-will** [comment]
I got the problem to reproduce, but for me it doesn't always show up as rank 0, as expected there is sometimes garbage data in there. That means that the cause is probably some messages from R3 getting lost, which would also be consistent with the fact that the problem occurs more often when the system is under heavy load. I will investigate more if it really is not arriving or if the data in it is somehow seen as the wrong datatype, and hopefully find a fix in the next few days.

 ![grafik](https://user-images.githubusercontent.com/57011129/172061992-73b25343-8bb8-451e-94b5-3d47d0ad1823.png)

**Comment by m-s-will** [comment]
It seems like the problem is that sometimes the first few values of the sent array are not received correctly, leading to a corruption of these specific vertices. I have changed some things and am currently testing if it still appears.
![grafik](https://user-images.githubusercontent.com/57011129/172350478-bbe52f24-017b-40f5-8de7-0a35c34e5e08.png)

**Comment by m-s-will** [comment]
Hi Eve,
please check out the PR, this (hopefully) fixes the error. I am currently on ~400 pipeline runs without the error appearing. Let me know if this or anything similar still appears for you.
Greetings,
Michael

**Comment by eve-le-guillou** [comment]
Hello Michael, 

Thank you for looking into this. 

I have compiled again using your code, and it does appear that the issue is no longer there. I have executed it over 50 times, while under heavy load.

Thank you very much!
Eve

**Comment by eve-le-guillou** [comment]
Seems like this issue has been corrected and the associated PR as been merged.
Thanks,

**Comment by eve-le-guillou** [comment]
Seems like this issue has been corrected and the associated PR as been merged.
Thanks,
