### ISSUE TITLE
[MPI] The `smooth` method of ScalarFieldSmoother only works for scalar field when using MPI

### ISSUE THREAD

**Issue by eve-le-guillou** [topology-tool-kit/ttk#830]
The `smooth` method of the TTK ScalarFieldSmoother class is used in two different filters: `ttkScalarFieldSmoother` and `ttkGeometrySmoother` of the VTK layer. 

In `ttkScalarFieldSmoother`, the `smooth` method is used to smooth whatever scalar field is given in input. In `ttkGeometrySmoother`, the `smooth` method is used to smooth the geometry itself, by modifying the coordinates of the points. 

Currently, the exchange of ghost data only works for scalar data: within `getGhostCellScalars`, the value associated to a point is assumed to be a scalar, therefore when trying to smooth the geometry in a 3D grid, not all coordinates of a point will be exchanged, resulting in incorrect results for the smoothing.

I believe @m-s-will implemented the MPI support of ScalarFieldSmoother. Would you have time to extend the MPI implementation to include the use case of the `ttkGeometrySmoother` filter?

Many thanks,
Eve

**Comment by m-s-will** [comment]
Sure I will check it out.

**Comment by m-s-will** [comment]
I extended exchangeGhostCells with the dimensionNumber similarly to `ttkGeometrySmoother`in PR #831 . Could you test this for me or send me a dataset used, as I only have a tetrahedralized wavelet and I'm not sure if I trust the tetrahedralization to give us good results there.
