### ISSUE TITLE
Non-deterministic, incorrect computation by FTM with a large number of cores

### ISSUE THREAD

**Issue by julien-tierny** [topology-tool-kit/ttk#841]
**Describe the bug**
FTM computes an incorrect result when used with a large number of cores.

**To Reproduce**
Run that python script (`bug.py`) within the ttk-data repository:
``` 
from paraview.simple import *

# create a new 'XML Image Data Reader'
ctBonesvti = XMLImageDataReader(FileName=['/home/julien/Pro/git/github/ttk-data-tierny/ctBones.vti'])
ctBonesvti.PointArrayStatus = ['Scalars_']

# create a new 'TTK PersistenceDiagram'
tTKPersistenceDiagram1 = TTKPersistenceDiagram(Input=ctBonesvti)
tTKPersistenceDiagram1.ScalarField = ['POINTS', 'Scalars_']
tTKPersistenceDiagram1.Backend = 'FTM (IEEE TPSD 2019)'
tTKPersistenceDiagram1.UseAllCores = 0
tTKPersistenceDiagram1.ThreadNumber = 1

SaveData("diagram_1thread.vtu", tTKPersistenceDiagram1)

# create a new 'TTK PersistenceDiagram'
tTKPersistenceDiagram48 = TTKPersistenceDiagram(Input=ctBonesvti)
tTKPersistenceDiagram48.ScalarField = ['POINTS', 'Scalars_']
tTKPersistenceDiagram48.Backend = 'FTM (IEEE TPSD 2019)'
tTKPersistenceDiagram48.UseAllCores = 0
tTKPersistenceDiagram48.ThreadNumber = 48

SaveData("diagram_48threads.vtu", tTKPersistenceDiagram48)
```

**Expected behavior**
Running 
```
python bug.py
diff diagram_1thread.vtu diagram_48threads.vtu
```
should not return anything.
On my laptop, which has only 6 physical cores, the two files are identical, **MOST OF THE TIME**.
On my desktop, which has 24 physical cores, the two files differ **MOST OF THE TIME**.

**Screenshots**
![screenshotBug](https://user-images.githubusercontent.com/3018628/195534231-f66fe9c6-89b8-4e4a-a0aa-4034f683aeaf.png)

**System (please complete the following information):**
- gentoo linux
- ttk dev

**Additional context**
This one is for @CharlesGueunet 
Thanks for your help!!!!

**Comment by julien-tierny** [comment]
In particular, when looking at the two files in ParaView, an obvious difference is that the global min-max pair is missing with 24 cores (see the above screenshot)
But that's not the only missing pair. 
The diagram on the left has 345,452 cells (information tab).
The one on the right has 276,343.

**Comment by julien-tierny** [comment]
Another observation: when my 24core system is busy (for instance, building some code in the background with a high number of threads), the computation is correct (as if, in that context, a racing condition was not happening due to the activity of the system).

**Comment by julien-tierny** [comment]
I confirm that #849 seems to do the trick (at least on one of my systems)

**Comment by julien-tierny** [comment]
I have the impression that performances drastically degraded on my 24 core system though.
running with 48threads is now as slow as 1 thread, with a very very long execution of `leafGrowth JT `:
- 1 threads, `leafGrowth JT` 1.858s
- 48 threads, `leafGrowth JT` 6.299s

**Comment by CharlesGueunet** [comment]
The changes in #849 should only impact the trunk, and not the `leafGrowth`, do you have any other change ?

**Comment by julien-tierny** [comment]
actually, we tried to revert this commit with @pierre-guillou and it turns out the problem was already there in the first place.
maybe the problem for this dataset was there was just too many threads and too much contention...
