### ISSUE TITLE
Windows VS 2017 build

### ISSUE THREAD

**Issue by nitawa** [topology-tool-kit/ttk#845]
Hi,
I am trying to build TTK on Windows 10 +  CMake 3.24.2 +  Visual 2017.
First it appears that one needs to patch DiscreteGradient_Template.h header file, otherwise the compilation will simply fail.
Patch is described below.
Next, I am using Boost built in a non standard way, which results in an issue when linking against the boost_date_time librarie.
I tried to set Boost_LIB_PREFIX to some empty string but it did not help.

       "D:\S\BUILD\TTK\core\vtk\ttkCinemaWriter\ttkCinemaWriter.vcxproj" (cible par d‚faut) (120) ->
       (Link cible) -> 
         LINK : fatal error LNK1104: impossible d'ouvrir le fichier 'libboost_date_time-vc141-mt-x64-1_67.lib' [D:\S\BUILD\TTK\core\vtk\ttkCinemaWriter\ttkCinemaWriter.vcxproj]

    25 Avertissement(s)
    1 Erreur(s)

In the end, I simply switched off two features: `-DVTK_MODULE_ENABLE_ttkCinemaWriter=NO` and `-DVTK_MODULE_ENABLE_ttkCinemaQuery=NO`
I can see that these options are currently in use in the azure-pipeline.yml file.
Do you know whether there is some known solution to this issue ? Are these features supported on Windows?
Thanks

Find below the patch aimed to resolve some namespace issues.
```
d:\S\ttk>git diff
diff --git a/core/base/discreteGradient/DiscreteGradient_Template.h b/core/base/discreteGradient/DiscreteGradient_Template.h
index f82f2f6a..0bc2167b 100644
--- a/core/base/discreteGradient/DiscreteGradient_Template.h
+++ b/core/base/discreteGradient/DiscreteGradient_Template.h
@@ -23,6 +23,7 @@ using ttk::dcg::CriticalPoint;
 using ttk::dcg::DiscreteGradient;
 using ttk::dcg::SaddleSaddleVPathComparator;
 using ttk::dcg::VPath;
+using ttk::VisitedMask;

 template <typename dataType, typename triangulationType>
 dataType DiscreteGradient::getPersistence(

```

**Comment by nitawa** [comment]
Hi
Indeed I was too optimistic. Windows compilation fails since it cannot build cinemaImaging (Memory header file not found even if present).
Can you share the recipe to build TTK (with vtk support) ?
Thanks,

**Comment by julien-tierny** [comment]
hi there, 
you may want to double check the windows continuous integration configuration file:
https://github.com/topology-tool-kit/ttk/blob/b1cb29a9c1c5010ac51c15b05480a2a2400d7e5b/.github/workflows/package.yml#L307
this will tell you how github builds ttk under its windows virtual machines.
I hope this helps.
