### ISSUE TITLE
Please add installation instructions for FreeBSD

### ISSUE THREAD

**Issue by yurivict** [topology-tool-kit/ttk#851]
Please add instructions to the [installation page](https://topology-tool-kit.github.io/installation.html):
* FreeBSD
   * Install from a package with ```pkg install ttk```

The FreeBSD port is now available: https://cgit.freebsd.org/ports/tree/science/ttk/Makefile

**Comment by julien-tierny** [comment]
thanks a bunch! 
it's been added on the website repo (it should take a few minutes to get online).
