### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by jhidding** [topology-tool-kit/ttk#88]
Building TTK on Fedora27 fails due to missing dependencies that were not picked up by cmake, namely:
- lz4
- protobuf
- pugixml
- cgns
After installing those, the build is successful!

**Comment by julien-tierny** [comment]
Dear Johannes,

thanks a lot for reporting this issue.

> Building TTK on Fedora27 fails due to missing dependencies that were not
> picked up by cmake, namely: - lz4
> - protobuf
> - pugixml
> - cgns
I see.
Package dependence indeed varies from one Linux distribution to the other. I 
guess these packages are installed by default on Ubuntu (hence not mentioned 
in our installation notes).

I'll update the installation procedure with a special note for Fedora users 
(and if you don't mind, I'll close the issue after that).
Thanks a lot for this input!

Thanks for letting us know if you need any help to use TTK.

Best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
Updated website.
