### ISSUE TITLE
Not able to run ctBones.pvsm 

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#92]
ctBones.pvsm with ctBones.vti doesn't seem to work on windows. It crashes.

**Comment by julien-tierny** [comment]
hi jonathan,

thanks for your feedback.

can you launch paraview from the 'Git Bash' command line interface?
(this terminal should be installed with default windows installs of git)

when you launch paraview from this terminal, you'll get to see in the output of the terminal all the debugging information.
can you copy paste that information in this discussion thread?

for info, you'll find the expected output below.

thanks for letting us know.

best,

[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[ImplicitTriangulation] The getVertex*() requests are accelerated.
[ttkPersistenceDiagram] Starting computation on field `Scalars_'...
------------
[FTM] number of threads : 24
* debug lvl  : 3
* tree type  : Join + Split
------------
[FTM] alloc in           0.925796
[FTM] init in            0.089263
[FTM] sort step in       0.327622
[FTM] leafSearch JT in   0.533292
[FTM] leafGrowth JT in   1.80177
[FTM] trunk JT in        0.320514
[FTM] leafSearch ST in   0.550122
[FTM] leafGrowth ST in   2.1926
[FTM] trunk ST in        0.37389
[FTM] merge trees  in    5.77426
[FTM] build tree in      5.77435
[FTM] Total  in          6.19152
[ttkPersistenceDiagram] Memory usage: 501.168 MB.
[ImplicitTriangulation] The getVertex*() requests are accelerated.
[TopologicalSimplification] Scalar field simplified in 28.3541 s. (24 threads(s), 1 ite.).
[ttkTopologicalSimplification] Memory usage: 62.6855 MB.
[ImplicitTriangulation] The getVertex*() requests are accelerated.
Launch on field : Scalars_
[FTM] number of threads : 24
[FTM] Total  in          2.28845
[ttkFTMTree] Memory usage: 350.964 MB.
[OneSkeleton] Edge-list built in 0.115766 s. (1517492 edges, 1 thread(s)).
[ZeroSkeleton] One-skeleton built in 0.255414 s. (24 thread(s)).
[ScalarFieldSmoother] Data-set (375389 points) smoothed in 0.064985 s. (24 thread(s)).
[ttkGeometrySmoother] Memory usage: 17.9043 MB.
[ttkSphereFromPoint] Spheres computed in 0.00655103 s.
[ttkSphereFromPoint] Memory usage: 0 MB.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
hi jonathan,

fyi this example seems to run fine under Windows with our batchmode pvsm state 
checker (see my previous email). can you please run the state checker as well 
to see if you still observe the same issue?
also, please use ttk's master branch for your tests (that would ease debugging 
on our end).

thanks for letting us know.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
dear jonathan,

our nightly checks have reported that the latest version of ttk's sources 
(master branch with ParaView 5.5) now manages to complete this example 
successfully under windows.
thus I'll close this issue for now.
please feel free to re-open it if you run into any further issue.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
