### ISSUE TITLE
[MPI] Crashes when using ImplicitTriangulation in 2D

### ISSUE THREAD

**Issue by m-s-will** [topology-tool-kit/ttk#929]
**Describe the bug**
Paraview crashes when trying to use the ImplicitTriangulation on 2-dimensional data.

**To Reproduce**
1. Run Paraview with mpirun with more than 1 rank
2. Use the 'Wavelet' filter to generate a 2D dataset
3. Use any filter accessing the triangulation e.g. ScalarFieldSmoother
4. Paraview will crash during PreconditionDistributedCells (see the attached screenshot)

**Expected behavior**
It should behave as in the 3D case, by e.g. smoothing the scalar field without crashing

**Screenshots**
<img width="802" alt="Bildschirm­foto 2023-05-04 um 17 13 12" src="https://user-images.githubusercontent.com/57011129/236251176-467e2991-4c1c-422f-9acf-7e1d2878d96d.png">

**System (please complete the following information):**
 - OS: Ubuntu 22.04
 - Paraview 5.10.1, current ttk-dev

**Additional context**
@emmwel encountered this problem a while ago and had some fixes, however different problems arose when trying to further work with the 2D data. She can give further context in the comments

**Comment by julien-tierny** [comment]
Thanks @m-s-will  for reporting this.
Can you please have a closer look into this? (e.g. which line is casing the segfault, what variable is not correctly set, etc.)

@eve-le-guillou have you run into this? any thoughts?

@pierre-guillou any thoughts?

thanks!

**Comment by emmwel** [comment]
The issue for me was that some variables overflowed when the dataset was 2D.

I did the following in ImplicitTriangulation.cpp:
* changed `createMetaGrid` to check whether the globalBounds for the third dimension is 0:

 ```
std::array<int, 3> dimensions = {
    static_cast<int>(
      std::round((globalBounds[1] - globalBounds[0]) / this->spacing_[0]))
      + 1,
    static_cast<int>(
      std::round((globalBounds[3] - globalBounds[2]) / this->spacing_[1]))
      + 1,
    static_cast<int>(
      std::round((globalBounds[5] - globalBounds[4]) / this->spacing_[2]))
      + 1,
  };

  if (globalBounds[4] == 0 && globalBounds[5] == 0) {
    // 2d
    dimensions[2] = 1;
  }
```
* changed `getVertLocalCoords` to only remove local grid offset for the third dimension if dimensionality is 3
```
/ local vertex coordinates
  p[0] -= this->localGridOffset_[0];
  p[1] -= this->localGridOffset_[1];
  if (this->dimensionality_ == 3)
    p[2] -= this->localGridOffset_[2];
```

With the above nothing crashes and seems to work as it should when comparing to serial results.

**Comment by m-s-will** [comment]
On further investigation, the crash appears here, and **only** if there are more than 2 ranks: 

https://github.com/topology-tool-kit/ttk/blob/731ed7cd29691cd2958d9bf574cb562a89bd17b6/core/base/implicitTriangulation/ImplicitTriangulation.cpp#L3177

So it probably has something to do with the neighborhood computation when you have multiple neighbors.

**Comment by julien-tierny** [comment]
@eve-le-guillou can you reproduce the issue? could you try out @emmwel's fix?

**Comment by pierre-guillou** [comment]
Hello everyone!

I have reproduced the issue on my laptop (2D Wavelet + ScalarFieldSmoother on 4 MPI processes). I get a segfault a bit earlier, at https://github.com/topology-tool-kit/ttk/blob/731ed7cd29691cd2958d9bf574cb562a89bd17b6/core/base/implicitTriangulation/ImplicitTriangulation.cpp#L3162

 Here the variable `cellRank` holds the value `-1`. Sadly, what @emmwel proposed does not seem to fix this issue.

After looking at what I've coded for the on-the-fly cell rank computation, I noticed that the `neighborCellBBoxes` overlap in a weird fashion. Those are computed through the `localBBox` reference and then exchanged between neighbors.

The culprit seem to be the call to `triangleToPosition2d` at https://github.com/topology-tool-kit/ttk/blob/731ed7cd29691cd2958d9bf574cb562a89bd17b6/core/base/implicitTriangulation/ImplicitTriangulation.cpp#L3117

When comparing `triangleToPosition2d` to `tetrahedronToPosition`, there's a divide by 2 missing in the former (a divide by 6 in the latter). Inserting a `p[0] /= 2;` at line 3118 seem to fix the issue.

Does this fixes the crash for you?

Pierre

**Comment by m-s-will** [comment]
Adding the division fixed the problem for me, however while testing it I found another issue, when forcing an explicit Triangulation by using Tetrahedralize beforehand. This leads to an endless loop in `exchangeDistributedInternal` (called from `preconditionDistributedEdges`, `doIter` doesn't seem to stay false, if we force the loop to finish after a few steps, the rest of the pipeline runs correctly, so the edges were preconditioned correctly), in 2D and 3D. I will investigate this further and maybe create another issue, this one seems fixed.

@emmwel does this fix work for you?

**Comment by emmwel** [comment]
Adding @pierre-guillou's fix worked for the ScalarFieldSmoother, but for the IntegralLines and our own filters I still need my own fix for the filters to work.

**Comment by m-s-will** [comment]
It turns out that the problem with IntegralLines and our filters had different sources, so the 2D problem should be fixed with the additional division.

**Comment by julien-tierny** [comment]
thanks a lot @pierre-guillou for the one-liner hot fix :)
would you mind opening a PR for that? 
(I can take care of that if you prefer)

**Comment by julien-tierny** [comment]
@m-s-will regarding the explicit triangulation, this is not something we have tested much. 
but that should definitely not be buggy as you report.
that'd be great if you could open a separate, detailed issue for that.
thanks!
