### ISSUE TITLE
Not able to run mechanical.pvsm 

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#95]
mechanical.pvsm with mechanical.vti doesn't seem to work on windows. It crashes.

Jonathan

**Comment by julien-tierny** [comment]
hi jonathan,

thanks for your feedback.

can you launch paraview from the 'Git Bash' command line interface?
(this terminal should be installed with default windows installs of git)

when you launch paraview from this terminal, you'll get to see on the output of the terminal all the debugging information. can you copy paste that information in this discussion thread?

for info, you'll find the expected output below.

thanks for letting us know.

best,

[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[Common]  _____ _____ _  __                       __  __    ____   ___  _  ___
[Common] |_   _|_   _| |/ /                      / /__\ \  |___ \ / _ \/ |( _ )
[Common]   | |   | | | ' /                      | |/ __| |   __) | | | | |/ _ \
[Common]   | |   | | | . \                      | | (__| |  / __/| |_| | | (_) |
[Common]   |_|   |_| |_|\_\                     | |\___| | |_____|\___/|_|\___/
[Common]                                         \_\  /_/
[Common] Welcome!
[ttkContinuousScatterPlot] U-component `magnitude'
[ttkContinuousScatterPlot] V-component `curl'
[ContinuousScatterPlot] Data-set (1482764 tetrahedra) processed in 3.11826 s. (24 thread(s)).
[ttkContinuousScatterPlot] Memory usage: 518.487 MB.
[ZeroSkeleton] Vertex stars built in 0.0643971 s. (1 thread(s)).
[OneSkeleton] Edge-list built in 0.249328 s. (1815377 edges, 1 thread(s)).
[ZeroSkeleton] Vertex edges built in 0.121297 s. (1 thread(s)).
[OneSkeleton] Edge stars built in 0.224585 s. (1815377 edges, 24 thread(s))
[ThreeSkeleton] Cell neighbors (1482764 cells) computed in 0.149224 s. (24 thread(s)).
[RangeDrivenOctree] Octree built in 0.272618 s.
[RangeDrivenOctree] Memory: 37.123 MB.
[ttkReebSpace] U-component: 'magnitude'
[ttkReebSpace] V-component: 'curl'
[ttkReebSpace] Starting computation...
[JacobiSet] Minimum edges: 3359
[JacobiSet] Saddle edges: 5061
[JacobiSet] Maximum edges: 3104
[JacobiSet] Multi-saddle edges: 0
[JacobiSet] Data-set (1815377 edges) processed in 0.733546 s. (24 thread(s)).
[JacobiSet] Jacobi edge rate: 0.634799%
[ReebSpace] 219 1-sheets and 1570 0-sheets extracted in 0.0145662 s.
[ReebSpace] Fiber surfaces computed in 10.7971 s. overall (24 thread(s)).
[ReebSpace] 4863 3-sheets computed in 3.46007 s.
[ReebSpace] Data-set (280248 points) processed in 15.0063 s. TOTAL (24 thread(s)).
[ReebSpace] Geometrical measures computed in 0.773549 s. (24 thread(s))
[ReebSpace] Data prepared for simplification in 0.0186939 s.
[ReebSpace] Sheet connectivity established.
[ReebSpace] Data prepared for simplification in 0.013099 s.
[ReebSpace] Simplifying with criterion 'Range Area' at threshold 0.05.
[ReebSpace] Data prepared for simplification in 0.00938106 s.
[ReebSpace] 4856 3-sheets simplified in 0.224294 s. (24 thread(s))
[ReebSpace] Last 3-sheet simplified at threshold 0.0424634
[ReebSpace] 7 3-sheets left.
[ttkReebSpace] Preparing the VTK-output...
[ttkReebSpace] Memory usage: 873.105 MB.
[ttkContinuousScatterPlot] U-component `magnitude'
[ttkContinuousScatterPlot] V-component `curl'
[ContinuousScatterPlot] Data-set (188574 tetrahedra) processed in 2.21024 s. (24 thread(s)).
[ttkContinuousScatterPlot] Memory usage: 78.4092 MB.
[ttkProjectionFromField] Data-set projected in 0.00302911 s. (39155 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.00295305 s. (59551 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.00237393 s. (4903 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.00324202 s. (120552 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.000152826 s. (10650 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] 0.00255395% processed....
[ttkProjectionFromField] 10.0013% processed....
[ttkProjectionFromField] 20% processed....
[ttkProjectionFromField] 29.9987% processed....
[ttkProjectionFromField] 39.9974% processed....
[ttkProjectionFromField] 49.9962% processed....
[ttkProjectionFromField] 59.9949% processed....
[ttkProjectionFromField] 69.9936% processed....
[ttkProjectionFromField] 79.9923% processed....
[ttkProjectionFromField] 89.9911% processed....
[ttkProjectionFromField] 99.9898% processed....
[ttkProjectionFromField] Data-set projected in 0.0229971 s. (39155 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.00139189 s. (31151 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[ttkProjectionFromField] Data-set projected in 0.000110865 s. (6546 points).
[ttkProjectionFromField] Memory usage: 0 MB.
[OneSkeleton] Edge-list built in 0.00382209 s. (39196 edges, 1 thread(s)).
[ZeroSkeleton] One-skeleton built in 0.00759411 s. (24 thread(s)).
[ScalarFieldSmoother] Data-set (13034 points) smoothed in 0.00355387 s. (24 thread(s)).
[ttkGeometrySmoother] Memory usage: 0 MB.
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by julien-tierny** [comment]
dear jonathan,

our nightly checks have reported that the latest version of ttk's sources 
(master branch with ParaView 5.5) now manages to complete this example 
successfully under windows.
thus I'll close this issue for now.
please feel free to re-open it if you run into any further issue.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
