### ISSUE TITLE
Not able to run oceanVortices.pvsm

### ISSUE THREAD

**Issue by jobordu** [topology-tool-kit/ttk#96]
oceanVortices.pvsm with oceanVortices.vtu doesn't seem to work on windows. It crashes.

Jonathan

**Comment by GuillaumeFavelier** [comment]
Hello,

I followed the [Windows installation instructions](https://topology-tool-kit.github.io/installation-windows.html) and installed TTK on my laptop, the only things I changed was the version of TTK (master branch) and ParaView (v5.5.0).

The Numpy package was not installed by default with Python so I installed it by opening a command prompt with administrator privilege and enter:
`pip install numpy`

With these modifications, I was able to run oceanVertices.pvsm successfully.

_Configuration: Windows 10, Intel dual-core CPU, 8 GB of RAM._

**Comment by julien-tierny** [comment]
hi guillaume,

thanks for your feedback.

can you prepare a pull request that would update the  the [Windows 
installation instructions](https://topology-tool-kit.github.io/installation-windows.html)  to optionally install numpy?

thanks!
julien
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by GuillaumeFavelier** [comment]
yes, sure. I'll work on it.

**Comment by julien-tierny** [comment]
thanks!
I'll close this issue for now.
please feel free to re-open it if you run into any further issue.

best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
