### ISSUE TITLE
Compile warning when building without graphviz

### ISSUE THREAD

**Issue by duncanspumpkin** [topology-tool-kit/ttk#981]
**Describe the bug**
[PlanerGraphLayout.cpp](https://github.com/topology-tool-kit/ttk/blob/31e8e3c303e2211aa320c66d71fa4f0c4a97ba0a/core/base/planarGraphLayout/PlanarGraphLayout.cpp#L3) performs an `#if` on the symbol `TTK_ENABLE_GRAPHVIZ` which is undefined when building without GraphViz. This will produce a warning if you have `-Wundef` enabled in gcc/clang. Instead it should be an `#if def` like on L21.

**To Reproduce**
1. Build without GraphViz on gcc/clang ensure `-Wundef` is enabled.
2. Notice warning

**Expected behavior**
No warnings produced.

**Comment by julien-tierny** [comment]
thanks duncan for these issues :)
please don't hesitate to submit a PR for tiny fixes like these.
cheers,

**Comment by duncanspumpkin** [comment]
> thanks duncan for these issues :) please don't hesitate to submit a PR for tiny fixes like these. cheers,

Will do when i have a moment.
