### ISSUE TITLE
TTK with a system-wide install of ParaView

### ISSUE THREAD

**Issue by jdumas** [topology-tool-kit/ttk#99]
Hi,

Is it possible to use TTK with a system-wide install of ParaView? I.e. where, as a user, I cannot edit the files installed in the root folder where ParaView is installed. Right now it seems there is a stage in the CMake (I supposed when you call `add_paraview_plugin()`) that is trying to edit some .txt file where ParaView is installed, and this fails because as user I don't have write access there. I mean this is very shaky behavior in general, and I would assume there is a way to have the plugins be installed in user-space without modifying the ParaView install? (I'm using ArchLinux for that matters.)

**Comment by julien-tierny** [comment]
hi jeremie,

thanks for your feedback.

> Right now it seems there is a stage in the CMake (I supposed when you call `add_paraview_plugin()`) that is trying to edit some .txt file where ParaView is installed, and this fails because as user I don't have write access there. 
what version of paraview is installed on your system?

we only observed this behavior with the latest version (5.5.0) and I believe this is an upstream bug (i.e. a problem with the latest paraview development files themselves).
obviously this is not a desirable behavior. 
this was not happening with earlier versions (e.g. 5.4.1).

@jpouderoux 
have you observed this too?

a workaround consists in performing a user install of ParaView (in a directory where you have write privileges) prior to installing ttk (in a user directory too).

of course, if you don't plan to use paraview at all, you can always disable paraview support in ttk's build (set TTK_BUILD_PARAVIEW_PLUGINS to OFF).

thanks for your feedback.
best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny

**Comment by jpouderoux** [comment]
Hi,

This is a know problem in PV 5.5 due to a recent change in VTK modules
management.
We partially fixed the issue in master with the following change:

https://gitlab.kitware.com/paraview/paraview/merge_requests/2366
<https://www.google.com/url?q=https://gitlab.kitware.com/paraview/paraview/merge_requests/2366&sa=D&source=hangouts&ust=1524644215101000&usg=AFQjCNG-zUM2Lby8dWD7GlbsM8LarHUQ9Q>

But it looks like there is still an issue with VTK modules.

Hope this helps,

Cheers,

Joachim

Le mar. 24 avr. 2018 07:33, Julien Tierny <notifications@github.com> a
écrit :

**Comment by jdumas** [comment]
Yes I was using [ParaView 5.5](https://www.archlinux.org/packages/community/x86_64/paraview/). Ok so let's hope this can be fixed in the next version of ParaView. I'll try to downgrade my version of ParaView in the meantime, but this is annoying (I wanted to try out the UI before going into the code).

Btw out of curiosity, the installation page of TTK suggests patching the source of ParaView. What is this patch doing exactly?

**Comment by jdumas** [comment]
Sure. I'll reopen if I run into trouble. Recompiling with the source of ParaView is annoying because you need to tell CMake where to look for ParaView, and make sure it doesn't catch the version installed on the system (or I need to remove the version on the system). Anyway, will let you know if I run into other issues.

**Comment by julien-tierny** [comment]
> Anyway, will let
> you know if I run into other issues.
ok, sounds good.
best,
-- 
Dr Julien Tierny
CNRS Researcher
Sorbonne Universite
http://lip6.fr/Julien.Tierny
